### ISSUE TITLE
Add an extra mark for Dubbed versions

### ISSUE THREAD

**Issue by littlebirdiegr** [sct/overseerr#2281] opened 2021-11-17 21:30 UTC
### Description

Hey awesome team,

So, at the moment we have 2 markings (one non-4k and one 4k), which is great. However, we do not have one for dubbed versions. Dubbed Versions are especially desired for cartoons for kids. It would be nice to have a button to _Request Dubbed_. 

### Desired Behavior

Example: 

User wants Despicable Me in a dubbed version. Despicable Me already exists in 1080p and 4K, so overseerr just shows play on Plex. A _Request Dubbed_ button would allow the user to ask this film in its dubbed version as well. I believe many users will find it useful.

Keep up the great work.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2021-11-17 21:50
I don't think this is the way to go about this.

Instead, I think that #1459 would cover this by making it possible to add another server with the appropriate default settings and letting the user choose that server if they want a dubbed version of that content.

**Comment by littlebirdiegr** [comment] 2021-11-17 22:14
> 
> 
> I don't think this is the way to go about this.
> 
> Instead, I think that #1459 would cover this by making it possible to add another server with the appropriate default settings and letting the user choose that server if they want a dubbed version of that content.

not really though. the issue you quoted is about something entirely different. But even if we did it your way what happens if the movie already exists on non-4k and 4k already in its original audio? There's no way to request another version simple as that.

**Comment by danshilm** [comment] 2021-11-17 22:21
Then the user creates an issue on that content. And an admin handles it from there.

About you saying that it's entirely different, is there something specific about what I said in my first comment that you see would not cover this issue?

**Comment by littlebirdiegr** [comment] 2021-11-17 22:29
Raise an issue, and an admin handles it? Thought the point for requesting stuff with overseerr is automation.

**Comment by danshilm** [comment] 2021-11-17 22:44
To a certain extent, yes. 

Seeing as the solution to #1459 will cover this, I'm closing this issue as a duplicate of the later.
You can subscribe to it to get notified of updates whenever we have any.

**Closed by danshilm** 2021-11-17 22:44 UTC
Labels: type:enhancement, awaiting-triage

**Comment by samwiseg0** [comment] 2021-11-17 23:28
> > I don't think this is the way to go about this.
> > Instead, I think that #1459 would cover this by making it possible to add another server with the appropriate default settings and letting the user choose that server if they want a dubbed version of that content.
> 
> not really though. the issue you quoted is about something entirely different. But even if we did it your way what happens if the movie already exists on non-4k and 4k already in its original audio? There's no way to request another version simple as that.

@danshilm is correct. This does cover your request. What you would do is have a 3rd server that is your “dubbed” server. Your users would then request against that server if they require a dubbed version.

**Comment by littlebirdiegr** [comment] 2021-11-18 01:07
But I already have connected my *arr with the dubbed versions and I can still not request the same movie that already exists on another *arr.

**Comment by littlebirdiegr** [comment] 2021-11-18 01:10
Overseerr marks it as available because both non-4k and 4k versions are existent, but what about the third dubbed version. There is no way to make a request for a 3rd version. The Request Buttons do not exist as Movie is already available on the two versions.

**Comment by TheCatLady** [comment] 2021-11-18 02:44
Shouldn't you just modify your *arr profiles so that it downloads media with your desired additional audio tracks?  Also, I agree with @danshilm that the issues feature in the upcoming release should be sufficient for this use case in instances that the desired audio is missing.
