### ISSUE TITLE
Seperate Root folder on a per user bassis

### ISSUE THREAD

**Issue by Pagnor** [sct/overseerr#1535] opened 2021-04-29 12:01 UTC
#### Description

A per user root folder so USER A could have tv requests sent to /path/to/root/USER A. And there requests would be placed there so if they request anime or documentary it wouldnt go to the default folder if you use seperate folders for tv folders.

"TV Ended
TV Current
TV Documentaries"

This is done in another software of the same kind and is a good feature for me and possibly others.

**Comment by sct** [comment] 2021-04-29 12:06
Duplicate of #609

**Closed by sct** 2021-04-29 12:06 UTC
Labels: awaiting-triage, type:enhancement
