### ISSUE TITLE
TV Show Discovery Filter - Error 500 with more than 1 Genre

### ISSUE THREAD

**Issue by Jarsky** [sct/overseerr#3285] opened 2023-01-27 03:04 UTC
### Description

The new Discovery Filter feature. When selecting Series and then trying to select more than 1 Genre it gives an Internal Error 500. 
It works fine for Movies, filtering by multiple Genre. 

Server is Ubuntu 22.04.1
Running in Docker 20.10.23 (image: sctx/overseerr:latest)

### Version

1.32.1

### Steps to Reproduce

1. Go to Series
2. Click on 'Active Filters'
3. Select a Genre e.g Action & Adventure
4. Select another Genre e.g Comedy

### Screenshots

![image](https://user-images.githubusercontent.com/839416/215001044-790f7ad6-2a8f-4d3b-8386-1753abe668e9.png)

![image](https://user-images.githubusercontent.com/839416/215000999-e1e57417-47b7-42ec-89e4-9d9239a7df28.png)

### Logs

```shell
There are no relevant logs generated in the overseerr.log file
```

### Platform

desktop

### Device

Desktop

### Operating System

Windows 11

### Browser

Chrome Browser

### Additional Context

Have tried it on multiple machines with different browsers.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-01-27 03:13
Duplicate of #3279

**Closed** 2023-01-27 03:14 UTC
Labels: type:bug, awaiting-triage

**Comment by Jarsky** [comment] 2023-01-29 01:56
Thank you, confirmed working on 1.32.2
