### ISSUE TITLE
Ability to hide/remove items from upcoming, popular, and trending lists

### ISSUE THREAD

**Issue by Kelmino** [sct/overseerr#1394] opened 2021-04-10 03:26 UTC
While I love the ability to display these lists (Especially the upcoming ones).  Currently my upcoming is filled with mostly Anime, Since I know no one who uses my server will request any of it, I'd love the ability to hide/remove items from these lists permanently.  With the ability to hide them globally it would make those options much more likely to be used.  They should still be available via a search just in case someone did decide to search for something.

**Comment by TheCatLady** [comment] 2021-04-10 03:28
Duplicate of #812

**Closed by TheCatLady** 2021-04-10 03:28 UTC
