### ISSUE TITLE
Invalid Discord user ID

### ISSUE THREAD

**Issue by niceguy4** [sct/overseerr#3003] opened 2022-09-04 14:50 UTC
### Description

Entering a 19-digit Discord User ID throws an error: "You must provide a valid Discord user ID". It will accept 18-digit, however, a person just created a new discord account and it now looks like discording is using 19-digit user IDs.

### Version

1.29.1

### Steps to Reproduce

1. go to [Users]
2. select [Edit] from a user in the [Select List]
3. copy a 19-digit user id from a discord user and paste the value into [Discord User ID]

### Screenshots

![tempsnip](https://user-images.githubusercontent.com/48399872/188319598-a9713963-c83d-4855-932d-ae32d3039a54.png)

### Platform

desktop

### Device

Computer

### Operating System

Windows 10

### Browser

Chrome and Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by niceguy4** [comment] 2022-09-04 15:47
Actually, it looks like this may have been resolved ? Just waiting for a server update.

https://github.com/sct/overseerr/pull/2860

**Comment by TheCatLady** [comment] 2022-09-04 16:14
Duplicate of #2989

**Closed** 2022-09-04 16:14 UTC
Labels: type:bug, awaiting-triage
