### ISSUE TITLE
Disable Plex sign-in and only allow local user sign-in

### ISSUE THREAD

**Issue by edbourque0** [sct/overseerr#3561] opened 2023-07-26 16:24 UTC
### Description

It would be great to be able to disable Plex sign-ins and only allow local users sign-in. Since all my users don't have a Plex account, I would want to force them to sign-in using their local account.

### Desired Behavior

In the Users section of the Settings page, add a setting to disable Plex sign-in. The login page would only have the local sign-in option

### Additional Context

I find the "Sign-in with local account" a bit hard to see on the login page. Maybe you could make it more evident

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment] 2023-08-03 19:29
Duplicate of #2557.

**Closed by OwsleyJr** 2023-08-03 19:29 UTC
Labels: type:enhancement, awaiting-triage
