### ISSUE TITLE
Custom Notification Text

### ISSUE THREAD

**Issue by bweezy21** [sct/overseerr#2798] opened 2022-06-02 16:41 UTC
### Description

Please allow admins the ability to add/modify text sent with all notifications.

### Desired Behavior

Add a section in the notification settings for admins to add/modify custom text.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-06-02 17:10
Duplicate of #405

**Closed by TheCatLady** 2022-06-02 17:10 UTC
Labels: type:enhancement, awaiting-triage
