### ISSUE TITLE
SABNzb integration 

### ISSUE THREAD

**Issue by jbeck22** [sct/overseerr#555] opened 2021-01-01 23:24 UTC
**Is your feature request related to a problem? Please describe.**
This is not part of a problem -- just a feature request.

**Describe the solution you'd like**
display the current download activity and or queue of SABNzb

**Describe alternatives you've considered**
Currently I have to navigate away from Overseerr to see what is downloading or not downloading.

**Additional context**
SABNzb already have API access built in

**Comment by Magikarplvl4** [comment] 2021-01-01 23:31
https://github.com/sct/overseerr/issues/417

**Comment by jbeck22** [comment] 2021-01-01 23:32
> #417

great.  Didn't see that before I posted.

**Comment by samwiseg0** [comment] 2021-01-02 02:31
Closing as it is a duplicate of #417

**Closed by samwiseg0** 2021-01-02 02:31 UTC
Labels: type:duplicate
