### ISSUE TITLE
Same notification each time sonarr sync runs has returned

### ISSUE THREAD

**Issue by Fiala06** [sct/overseerr#924] opened 2021-02-13 17:14 UTC
**Describe the bug**
Bug has come back: https://github.com/sct/overseerr/issues/777

Each time I run the sonarr sync I receive a notification for a show that hasn't changed or new episodes added. 

I've tried "re-matching" in Plex and still get the notification. Dirty Jobs is the only show this happens for. 

**What version of Overseerr are you running?**
Latest Dev: develop-04fa9f79e2ec90082b3fa15590dd170f7d68ad52
Has been happening since sonarr sync feature was added

**To Reproduce**
Unsure as it's only happening for 1 show weather I manually run the sonarr sync or it auto runs every 24hrs. 

**Expected behavior**
Shouldn't be getting the same notification over and over.

**Screenshots**

![image](https://user-images.githubusercontent.com/5183146/107856169-4c483c80-6ddb-11eb-89ee-b0d463f45400.png)

![image](https://user-images.githubusercontent.com/5183146/107856189-6aae3800-6ddb-11eb-8d81-d7d1141ec149.png)

![image](https://user-images.githubusercontent.com/5183146/107856206-86b1d980-6ddb-11eb-8016-7b10b702243d.png)

![image](https://user-images.githubusercontent.com/5183146/107856220-9d583080-6ddb-11eb-8471-f6ccf39559aa.png)

**Desktop (please complete the following information):**
UNRAID

**Smartphone (please complete the following information):**
 N/A

**Additional context**
Logs: https://gist.github.com/Fiala06/01113c4eb1205ceacbc25bf36cc2d7b9

**Comment by sct** [comment] 2021-02-14 12:06
Duplicate of #872

**Closed by sct** 2021-02-14 12:06 UTC
Labels: awaiting-triage, type:bug
