### ISSUE TITLE
Default Anime Server

### ISSUE THREAD

**Issue by m0dd3r43v3r** [sct/overseerr#3639] opened 2023-10-06 12:15 UTC
### Description

It would be awesome if we could have a checkbox in the Services Settings to select a sonarr instance that is dedicated to Anime like the 4k Checkbox.

It would be also awesome if there was logic that if the request is labeled as Anime that it would automatically be sent to that service.

### Desired Behavior

Check box for Default anime that is used whenever anyone requests a Anime Series

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment] 2023-10-09 14:30
Duplicate of #2876.

**Closed by OwsleyJr** 2023-10-09 14:30 UTC
Labels: type:enhancement, awaiting-triage
