### ISSUE TITLE
Notes for Denied Request

### ISSUE THREAD

**Issue by odin-bb** [sct/overseerr#1171] opened 2021-03-14 16:41 UTC
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

#### Desired Behavior

I would love to be able to provide a justification as to why a request was denied. Like a text box. 

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by samwiseg0** [comment] 2021-03-14 16:55
Dupe of https://github.com/sct/overseerr/issues/593

**Closed by samwiseg0** 2021-03-14 16:55 UTC
Labels: awaiting-triage, type:enhancement
