### ISSUE TITLE
Option to include username of user who submitted the request in the tag

### ISSUE THREAD

**Issue by sleepymatto** [sct/overseerr#2444] opened 2022-01-20 09:24 UTC
### Description

I'm having trouble keeping track of which users requested what once it's been added sonarr/radarr. I am constantly going back and forth between radarr/sonarr and overseer to try and match up who requested what.

### Desired Behavior

I think it would be great if we could have the option to set the tag as the username of the person who submitted the request. Or maybe the option to use variable in the tag such as: overseer-{username}. Now when you are going through your lists of movies/tv shows in sonarr/radarr, you would be able to quickly see and sort by who requested what.

### Additional Context

Thanks for all the work you have put into this. This has made my life so much easier not having to deal with requests manually. Also love how the app is designed .. it's easy to use and looks beautiful. Great work!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2022-01-20 10:36
Duplicate of #1964. Follow that issue for updates.

**Closed by danshilm** 2022-01-20 10:36 UTC
Labels: type:enhancement, awaiting-triage
