### ISSUE TITLE
Similar Titles in loop

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#1363] opened 2021-04-05 03:50 UTC
#### Description

The "Similar Titles" page, different from Recommendations, keeps looping on the same titles.

#### Version

develop-35c13a87467b4deabab3cb2cd1cab1b24ab51875

#### Steps to Reproduce

1. Open the page of a movie
2. Click on Similar Titles
3. Scroll down and you'll see that after about 20 movies, Overseerr keeps loading the same results over and over.

#### Expected Behavior

Is expected that Similar Titles behaves like Recommendations page where movies don't repeat after the list is finished.

#### Screenshots

![ksnip_20210404-234801](https://user-images.githubusercontent.com/50637431/113535022-46cbcf00-95a0-11eb-9bb8-03c1a20b1176.png)

#### Device

- **OS:** Fedora 33
- **Browser:** Brave 1.22.71

**Comment by sct** [comment] 2021-04-05 12:01
Odd. I am able to reproduce. We haven't touched this in a while so I am confused why this started happening. I will investigate.

**Comment by sct** [comment] 2021-04-05 12:16
So it's actually TMDB that's currently doing this. The page parameter for their similar movie/tv API is not working it seems. It always returns the first page. I imagine this will be fixed before long.

**Comment by TheCatLady** [comment] 2021-04-06 01:21
@sct Do we want to revisit the idea of de-duping results?  Wouldn't fix this issue since we'd still constantly make requests for more data and keep getting page 1 of the results back, but at least the user would only see one copy of each result.

**Comment by sct** [comment] 2021-04-06 02:58
> @sct Do we want to revisit the idea of de-duping results? Wouldn't fix this issue since we'd still constantly make requests for more data and keep getting page 1 of the results back, but at least the user would only see one copy of each result.

I don't want to do this because its a lot of processing that needs to happen on the frontend for it to work. It's something that occurs very infrequently so its not worth the engineering effort (or the extra strain put on peoples systems)

As for this ticket, I am closing it for now because it's out of our hands.

**Closed by sct** 2021-04-06 02:58 UTC
Labels: invalid:not-overseerr-issue
