### ISSUE TITLE
[BUG] Memory leak when creating "issues", with TV Shows that have large season numbers

### ISSUE THREAD

**Issue by VP-EN** [sct/overseerr#2491] opened 2022-01-29 23:41 UTC
### Description

Hi!

Whenever you create issues (and try to view the issue created afterwards) with a TV Show, that has high season numbers, like `Season 2003`, `Season 2004` and so on, Overseerr/nodejs will take up **loads** of memory within seconds.

### Version

v1.28.0 (snapcraft) 

### Steps to Reproduce
**16/02/2022** - Slight update

1. Login to Overseerr
2. Find a show with a large season number
3. In my case, MythBusters
4. Create an issue for `Season 2003`
5. Select All Episodes and Issue: Video
6. Press Submit
7. Either press "view issue" immediatly after creating it.
  -- or --
8. Press on the "Issue" tab, to view all created issues.
9. Watch as your RAM usage explodes

### Screenshots

**Creating the issue**
https://imgbox.com/dwZoteT7

**Trying to access the Issue tab after running a** `sudo snap restart overseerr`
https://imgbox.com/VFTii82t

(updated the links, imgur is buggy atm)

### Platform

Overseerr is running on Ubuntu 21.10/impish 

### Device

Desktop

### Operating System

Windows 11

### Browser

Firefox

### Additional Context

No relevant logs this time.
Started from this thread:
https://discord.com/channels/783137440809746482/789002037529804833/937119741376626719

Ending up creating this GH issue instead.

**Edit - 16/02/2022**
- If you run in to the same issue, and wondering how to edit your .db file, here's a short guide for Linux. I don't use my `root` user, so I just use `sudo` with my "local"/"home" user:

**Quick guide to fix the DB file**
So to clean the DB I used just a simple DB viewer / DB editor.
In my case, I just chose the first one I found: 
<https://github.com/sqlitebrowser/sqlitebrowser>

The .db file usually lies in the `/root/snap/overseerr` folder if you're using Linux.
In my case, it lies in: `/root/snap/overseerr/common/db`

To be safe, shutdown the overseerr instance: `sudo snap stop overseerr`

Just download all the files in there. 
Or copy them: `sudo cp -R /root/snap/overseerr/common/db /home/user/path/db` and `chown -R user:user /home/user/path/db`, if you don't use your root user.

Open the `db.sqlite3` with your DB viewer. If you use the one above, follow these steps to find the issue you want to delete (the one with the large season number):
1. Open the `db.sqlite3` with DB Browser for SQLite
2. Select the `Browse Data` `tab
3. Find the `Table` and select `issue`
4. Find the issue with a large season number, and delete it
5. Save the db-file. You'll be left with just the `db.dqlite3` file in the folder you edited the db file in.

Then purge/delete the old `.sqlite3*` files in `/root/snap/overseerr/common/db` and re-upload the db file to whatever directory.
Then copy the `db.sqlite3` file back to the `/root/snap/overseerr/common/db` with `sudo cp db.sqlite3 /root/snap/overseerr/common/db`, and remember to chown it back to the root user with `sudo chown -R root:root /root/snap/overseerr/common/db`.

Start/restart overseerr again `sudo snap start overseerr`, and rejoice that you can go into your issue section again, without everything crashing:
.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-02-08 03:52
Huh, seems weird that you have those season numbers in the first place. 🤔 They are listed as seasons 1-16 on TMDb.

Can you try clearing the media data for that show, running a full Plex scan, and then trying to reproduce the issue?

**Comment by VP-EN** [comment] 2022-02-08 09:15
> Huh, seems weird that you have those season numbers in the first place. 🤔 They are listed as seasons 1-16 on TMDb.
Pretty sure I added it through Sonarr. Not sure if that makes any difference, but I think it uses [TheTVDB](https://thetvdb.com/series/mythbusters), which has the seasons listed as 2003, 2004 and so on.

> Can you try clearing the media data for that show, running a full Plex scan, and then trying to reproduce the issue?
Yes! Will do 😄 

> And provide logs, please.
**Before doing the suggested:**
Logs for creating the issue and system exploding (before doing what you suggested):
https://0bin.net/paste/DMncJm0R#3A1hV5jonnGDoYAK7xqjoDU7-T9vMdrx/Qsnaaj6wyb

This is just after a `sudo snap restart overseerr`, making a note of the time (`2022-02-08T08:25:39.845Z`), and then creating the issue. 
Then the RAM usage explodes as shown in the GIFs. These logs are from just after I restarted.
At some point, Overseerr restarts itself, since the page opened suddenly goes 503 Services Unavailable and the RAM usage resets to normal levels.

I also tried looking at the logs after a manual `sudo snap restart overseerr`, and then trying to access the "Issues" submenu in Overseerr - but there was no changes in the logs from that endeavor.

Tried to upload the entire log file to gist github, but that didn't work out. Uploaded them [here](https://bayfiles.com/JcM0D2G8x8/overseerr-2022-02-08_7z) if there's any interest. Password is `overseerr`. A lot of irrevelant things IMO, since I restarted the server, and created the issue at the time noted above.

Interestingly enough, I noticed that the "RAM exploding" only happens when you either view the issue, just after creating it, or if you click on the "Issues" submenu. It doesn't "explode" just by creating issue, only by either viewing it after you create it, or by going into the Issue submenu after creating it.

**After doing the suggested:**
So I reuploaded the `db.sqlite3` without the MythBusters season 2003 issue in it, then cleared the media data for MythBusters, and initiated a Full Plex Scan.

Looked through the logs, searching for "MythBusters":
```
2022-02-08T09:06:51.186Z [debug][Plex Scan]: Saved MythBusters 
``` 

Found MythBusters in Overseerr, but it showed up as not existing. So I just marked it as available.
And the seasons are back to "normal"! Now it doesn't show up as TheTVDB/Sonarr, not it shows up as season 01, season 02, etc.


Afterwards I created the issue, here are the logs: 
https://0bin.net/paste/Kv8bENzz#MNLj8W2twGPC3qC2vWtOuVgk+RuXIMhDxWTbQO8Q3Ta

And **no** RAM explosion this time. Which is great. Just wondering why it created MythBusters with the large season numbers?
And I'm also getting worried if I should have other TV shows laying around with large season numbers 😰 

And here it is, including the full Plex scan:
https://bayfiles.com/F6dcE4G6x1/overseerr-2022-02-08-afterScan-afterIssue_7z
Password `overseerr`

**Comment by TheCatLady** [comment] 2022-02-08 14:28
> **Notes** Just wondering why it created MythBusters with the large season numbers? And I'm also getting worried if I should have other TV shows laying around with large season numbers 😰 Pretty sure I have a few. Most created through Sonarr I think.

I think the issue is that the Sonarr scan has not been verifying that season numbers match those on TMDb before adding them to the DB.  Just submitted a fix for this in #2523 so that new shows shouldn't be added with these incorrect season numbers (but this won't fix existing shows).

That said, we haven't figured out _why_ these odd season numbers are causing an issue...

**Comment by VP-EN** [comment] 2022-02-08 16:24
> I think the issue is that the Sonarr scan has not been verifying that season numbers match those on TMDb before adding them to the DB. Just submitted a fix for this in #2523 so that new shows shouldn't be added with these incorrect season numbers (but this won't fix existing shows).

Guess I'll go on a season hunt, or maybe just rescan everything. A total Overseerr wipe might be in order, just to be safe 😄. 

> That said, we haven't figured out _why_ these odd season numbers are causing an issue...

Yeah, that's really weird. Not sure I can help much more than logs and GIFs already provided. If I can, I'll gladly help. But I don't see anywhere of increasing the logging level(s), and the debug logs doesn't really give much information about what's happening, other than a line or two about the issue getting created.

**Comment by TheCatLady** [comment] 2022-02-08 16:37
> Guess I'll go on a season hunt, or maybe just rescan everything. A total Overseerr wipe might be in order, just to be safe 😄. Obviously after the the fix has been implemented into the stable releases

The Overseerr scans wouldn't remove items, unfortunately.  If you're comfortable performing DB operations, you could locate problematic media by querying the `Season` table for season numbers greater than some sane value.

**Comment by VP-EN** [comment] 2022-02-08 17:50
> > Guess I'll go on a season hunt, or maybe just rescan everything. A total Overseerr wipe might be in order, just to be safe 😄. Obviously after the the fix has been implemented into the stable releases
> 
> The Overseerr scans wouldn't remove items, unfortunately.  If you're comfortable performing DB operations, you could locate problematic media by querying the `Season` table for season numbers greater than some sane value.

I'll probably do that, if not a full wipe.

A bit off topic maybe, but what would happen (after your fix) if a series has e.g. Season 2003 and so on in tvdb, but doesn't exist at all in tmdb? I could imagine that happening for foreign language content.

**Comment by TheCatLady** [comment] 2022-02-08 17:57
> A bit off topic maybe, but what would happen (after your fix) if a series has e.g. Season 2003 and so on in tvdb, but doesn't exist at all in tmdb? I could imagine that happening for foreign language content.

Those seasons would no longer get added to the DB by the Sonarr scan. But, this is good since otherwise the same seasons numbered differently could be added by the Plex scan as well, resulting in duplicates.

In cases where Overseerr cannot find media for TMDb seasons, you'd need to manually mark the series as available, but this is currently the case as well.

**Comment by VP-EN** [comment] 2022-02-10 22:20
Not sure if this is going too off-topic, but I ended up going digging, just to see if it was a regular occurence in my Overseerr db.

Found a few shows in the db file lol, all these have seasons with 1900-2000+.
```
# TMDb 1428   || TheTVDB 73388   [mediaId: 10860]   [MythBusters (2003)]
# TMDb 2912   || TheTVDB 77075   [mediaId: 14915]   [Jeopardy! (1984)]
# TMDb 4384   || TheTVDB 80646   [mediaId: 14933]   [Frontline (1983)]
# TMDb 4994   || TheTVDB 70730   [mediaId: 14963]   [Biography (1987)]
# TMDb 66249 || TheTVDB 310319 [mediaId: 6786]     [King of the Road (2016)]
# TMDb 96502 || TheTVDB 338705 [mediaId: 10245]   [Natholdets julekalender (2017)]
```

Seems the https://github.com/sct/overseerr/pull/2523 fix has been merged into `develop`. So, after next stable release, if I wipe my Overseerr setup and scan it all over, will these series be scanned in with the TMDb ids instead? (atleast those who has an available TMDb match/id).

Also, any progress into finding the "root cause"? 😄 .

**Comment by TheCatLady** [comment] 2022-02-10 22:27
> Seems the #2523 fix has been merged into `develop`. So, after next stable release, if I wipe my Overseerr setup and scan it all over, will these series be scanned in with the TMDb ids instead? (atleast those who has an available TMDb match/id).

They will only get picked up if they are added with the TMDb season numbers in Plex.  Otherwise, you'll need to manually mark them as available.  (If you want to discuss this issue further, Discord may be a better place to do so, so we can keep this issue on-topic.)

**Closed** 2022-03-12 21:05 UTC
Labels: type:possible_bug, more_info_requested

**Comment by sbrown7792** [comment] 2022-06-22 20:52
In case this gets re-opened when someone is able to reproduce it: I was hit by the same symptoms described here, except the trigger was a Request for a TV show with 176 seasons. House Hunters International (and yes, they're numbered 1-176 on TMDb 🙄 the "why" is beyond me...). And since "requests" appear on the main page (under "Recent Requests"), I didn't have to browse to any other page to trigger the memory "explosion" and subsequent crash:

`2022-06-22T19:43:25.144Z [debug][Jobs]: Starting scheduled job: Download Sync 
<--- Last few GCs --->
[28:0x7f06f676c340]   255995 ms: Mark-sweep (reduce) 4066.0 (4143.8) -> 4065.1 (4143.8) MB, 2019.3 / 0.0 ms  (average mu = 0.708, current mu = 0.006) allocation failure scavenge might not succeed
[28:0x7f06f676c340]   257923 ms: Mark-sweep (reduce) 4066.3 (4143.8) -> 4065.5 (4144.0) MB, 1916.4 / 0.0 ms  (average mu = 0.556, current mu = 0.006) allocation failure scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.18
$ NODE_ENV=production node dist/index.js
`

I am running in Docker on linux, version 1.29.1

I was able to delete the relevant media_request and season_request rows by using the sqlite3 db client, which then let me browse the overseerr GUI without it crashing. Unfortunately I wasn't able to reproduce after re-adding the request (after clearing data for the show), or adding an issue relating to the series (after doing a full Plex scan).

**Comment by coreylane** [comment] 2022-07-12 04:10
Ran into the exact same issue with House Hunters International on `1.29.1`
