### ISSUE TITLE
Deleting in Overseerr also deletes in Sonarr/Radarr

### ISSUE THREAD

**Issue by boultonn** [sct/overseerr#1196] opened 2021-03-15 23:29 UTC
#### Description

Deleting an item in Overseerr also deletes the linked item in Sonarr/Radarr to avoid a build-up of unwanted titles, and so it doesn't have to be removed in multiple places.

#### Desired Behavior

When deleting a previously approved item, either automatically delete from Sonarr/Radarr too, or provide a prompt or configuration parameter to specific whether the item is deleted from Sonarr/Radarr and if this includes deleting the files too.

#### Additional Context

None.

**Comment by samwiseg0** [comment] 2021-03-15 23:34
Thanks for opening a new issue!

**Comment by sadstan123456** [comment] 2021-06-04 16:06
I would love this to be added. Pls don't mark it as stale, stale-bot

**Comment by jrucker2004** [comment] 2021-07-06 18:51
If this is implemented, please make it optional.  I don't want deleting a request to delete things on radarr, sonarr, or my file server.

**Comment by modem7** [comment] 2021-08-06 17:36
I'd actually prefer it the other way round, where deleting items in *arr deletes in overseer.

That'd make more sense from a workflow perspective.

**Comment by douglasparker** [comment] 2021-10-05 23:31
.

**Comment by richard-lee-863** [comment] 2021-10-18 22:44
I am a fan of this idea. I like to expose Overseerr to my users so they can easily request things, but as an admin i would also like to manage media here. 
The fact that Overseerr can sync with Plex library to keep up to date record on which files are actually present makes a good case for deletions to be managed here too. I don't believe Radarr has as nice a sync feature. 

As an admin i'd like to manage the higher level stuff in one place, but i can see the other side of the coin of managing deletions in Sonarr/Radarr too. 

I guess its more useful to have this feature when dealing with a small HDD Seedbox, as opposed to people who have large storage and intend to keep things around.

**Comment by richard-lee-863** [comment] 2021-10-18 23:31
Ah i thought that is what is being presented by the "Recently Added" data, which is populated from running the "manual library scan"?

**Comment by dedworks** [comment] 2021-11-26 05:05
> Deleting an item in Overseerr also deletes the linked item in Sonarr/Radarr

This is the opposite of what I saw, I was thrown off by the fact that it *didn't* delete the linked item for me.

https://github.com/sct/overseerr/issues/2305#event-5675608181

**Comment by douglasparker** [comment] 2021-11-26 06:04
> > Deleting an item in Overseerr also deletes the linked item in Sonarr/Radarr
> 
> This is the opposite of what I saw, I was thrown off by the fact that it *didn't* delete the linked item for me.
> 
> https://github.com/sct/overseerr/issues/2305#event-5675608181

I think that's what is being requested here. I know it's worded weird. Just read **Desired behavior** in the issue.

**Comment by TheCatLady** [comment] 2021-11-26 15:49
As per internal team discussion, closing this.  Sorry folks!  This is really a duplicate of another declined feature request #1924, just via the *arrs.

**Closed by TheCatLady** 2021-11-26 15:49 UTC
Labels: topic:ux, topic:backend, type:enhancement, priority:low

**Comment by dedworks** [comment] 2021-11-27 05:17
> As per internal team discussion, closing this. Sorry folks! This is really a duplicate of another declined feature request #1924, just via the *arrs.

Seems like #1824 was rejected for wariness of destroying data which is a great decision. 

This request is not similar. It can't destroy data, it only involves selection of what will be downloaded in the future, which is precisely what overseerr is for (if I'm not mistaken). 

What possible motivation could one have to delete a request, if it will not stop the disk from filling?

It's no use to remove the entry from overseerr's request history, if it won't stop the *arrs from consuming every last bit of the resources it would if I didn't delete it.

**Comment by TheCatLady** [comment] 2021-11-27 06:55
> This request is not similar. It can't destroy data, it only involves selection of what will be downloaded in the future, which is precisely what overseerr is for (if I'm not mistaken).
This is not true.  A request could be deleted after the media has already become available or partially available, in which case this could be a destructive action.

> What possible motivation could one have to delete a request, if it will not stop the disk from filling?
Deletion of requests is not intended to be performed on a regular basis.  Overseerr wants to keep a record of requests for features like quotas.  On the rare occasions an approved request needs to be canceled, the item should be deleted on the *arr side.  It is planned for Overseerr to detect deleted items during scans in the future, but there are no plans to support initiating media deletion from within Overseerr.

**Comment by jaschuu** [comment] 2024-05-31 10:12
"It is planned for Overseerr to detect deleted items during scans in the future"

Has this been done or had a date for when it will be?

**Comment by abranski** [comment] 2024-06-14 16:09
I agree 100%. If the overseer is the entry point to the entire ecosystem and has the ability to add new items, it MUST have the ability to remove them. Otherwise, its operation becomes unintuitive.

**Comment by Skepmeister** [comment] 2025-06-14 14:13
Just have an option and let the user decide.  I would like to see requests that I delete in overseer also delete the sonarr and radarr as well.  I know this is not for everyone, but give me the option to do that if I choose.

**Comment by modem7** [comment] 2025-06-14 14:41
> I would like to see requests that I delete in overseer also delete the sonarr and radarr as well.  I know this is not for everyone, but give me the option to do that if I choose. 

That will never happen. There have been many discussions on that topic, and the developers feel that overseer shouldn't be the software to manage your media, and have categorically stated they won't be implementing that. 

Maintainerr is probably the best tool for this, but at least now, if you delete things in the *arrs, it shows up as deleted in overseer and that's pretty Aight for what the scope of overseer is for.
