### ISSUE TITLE
Hide Available Media (Experimental Feature) Actor/Actress page issues

### ISSUE THREAD

**Issue by dmei4380** [sct/overseerr#3239] opened 2023-01-13 21:38 UTC
### Description

Hide Available Media Experimental feature issue:

**Preface: I know this is an experimental feature and am in no way asking for it to be fixed. I didn't notice a report for this in open issues and I didn't see anywhere else to report experimental feature bugs.**

Available Movie/Series not being hidden, and status does not render available icon (will show requested icon if it isn't in plex) only when viewing an actor/actress profile. It also still shows a request button when hovering over an object (Screenshot 4) and returns an error when trying to request the already available item (Screenshot 5). This works on any other page (available icon is shown and request button is appropriately hidden) such as discovery page, viewing the marvel studios page

The items are appropriately hidden when viewing something like the Marvel Studios page or Discovery. When doing a search for an available item, it does show up (as it probably should) but also appropriately shows the available icon and removes the request button.

Items render appropriately when experimental setting is turned off, so a few things to consider:

1. If actor/actress pages should show content that is available regardless of the "Hide Available Media" setting, it should also appropriately show the available icon and hide the request button on hover.
2. Should the studio pages and search show available media regardless of the "Hide Available Media" setting
3. If all pages should hide all available media, at least studio pages and actor/actress pages (and maybe a search page) should behave similarly

### Version

1.31.0 (running in docker container)

### Steps to Reproduce

1. Ensure Hide Available Media (Experimental) feature is enabled
2. Go to any actor/actress profile and ensure a movie or series is listed as available (Screenshot 1 shows black panther is available in plex, Screenshot 2 shows Black Panther Wakanda Forever is requested)
3. Navigate to Actor/actress page and notice a request item shows the icon in upper right, but the available item is still shown in the listbut does not have an available icon (Screenshot 2, notice there is no icon on Black Panther on Letitia Wright's Actress page (area circled in red)

### Screenshots

![image](https://user-images.githubusercontent.com/21084213/212416896-eb9c9d1c-1f2a-41c5-9068-6927205b424d.png)
![image](https://user-images.githubusercontent.com/21084213/212417004-eb982f93-5fbb-4ef5-8fa2-10a0c6fbaac9.png)
![image](https://user-images.githubusercontent.com/21084213/212417574-6beca91d-f0da-41d6-8630-0a9d409ca723.png)
![image](https://user-images.githubusercontent.com/21084213/212418414-b1999534-4714-4168-bbef-f0f2e6b90f31.png)
![image](https://user-images.githubusercontent.com/21084213/212418547-1f919091-c077-49f0-9738-8b4f21e8f694.png)

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Chrome

### Additional Context

Also does the same on iPhone iOS 16.1 Safari Browser

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-01-13 22:49
Duplicate of #3088

**Closed by TheCatLady** 2023-01-13 22:49 UTC
Labels: type:bug, awaiting-triage
