### ISSUE TITLE
Discord notificaiton on new episode download

### ISSUE THREAD

**Issue by BigJazzz** [sct/overseerr#3323] opened 2023-02-06 10:21 UTC
### Description

I get asked fairly regularly to check if the latest episode has been downloaded for a given TV show. Being able to set notifications for new episodes that tag the requester would be handy, especially if you can push them to a separate channel from the requested/approved/available channel.

I've seen a few different issues/requests raised that are similar to this, but the only one that came close is #2097. However this one focuses on season availability, not episode.

### Desired Behavior

* Add a per-user "Episode available" notificiation node
* Specifiy an optional secondary Discord channel for episode availability notifications
* Post to the channel tagging the requester when a new episode is available

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-02-06 18:19
Duplicate of #342 (episode notifications will come with episode request support)

**Closed by TheCatLady** 2023-02-06 18:19 UTC
Labels: type:enhancement, awaiting-triage

**Comment by BigJazzz** [comment] 2023-02-07 01:11
Ahhhh. Thanks @TheCatLady. I missed that one. Soz!
