### ISSUE TITLE
Rotten tomatoes/TMDB score to appear on discover page

### ISSUE THREAD

**Issue by absywabsy** [sct/overseerr#1462] opened 2021-04-18 12:44 UTC
#### Description

Hi, it's great to see the rotten tomatoes score when you click **into** a movie but it would be nice to see the scores on the front page when you're simply browsing movies.

I think it would be a really cool feature to have the rotten tomatoes and TMDB scores to appear on the front page of Ombi, just underneath or on top of the movies.

This would allow users to quickly pick out the good tomatoes and request it.

#### Desired Behavior

You could have it displayed static when you're on the landing page or you could have it only appear when the user places their mouse over the movie.

#### Additional Context

Here's how I think it would look, I whipped up an image with an image editor:

https://i.imgur.com/ASkYjaU.png

**Comment by danshilm** [comment] 2021-04-18 16:09
This is hilarious:

> I think it would be a really cool feature to have the rotten tomatoes and TMDB scores to appear on the front page of **_Ombi_**

**Comment by TheCatLady** [comment] 2021-04-18 17:24
Duplicate of #306

**Closed by TheCatLady** 2021-04-18 17:24 UTC
Labels: awaiting-triage, type:enhancement
