### ISSUE TITLE
Search via URL redirects to the home page

### ISSUE THREAD

**Issue by mikedodge04** [sct/overseerr#2996] opened 2022-08-29 18:10 UTC
### Description

when using the search feature with a URL  like the example below, you see the search load, but then overseer redirects to the home page. 

Example:
https://overseer.domain.com/search?query=%s 
https://overseer.domain.com/search?query=batman

### Version

1.29.1

### Steps to Reproduce

1. Goto this like with your correct domain. https://overseer.domain.com/search?query=batman

I would expect the search to load. But you see a flash of the search and then you see the home page. 

### Platform

desktop

### Device

*

### Operating System

*

### Browser

*

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-08-29 18:47
Duplicate of #2683

**Closed by TheCatLady** 2022-08-29 18:47 UTC
Labels: type:bug, awaiting-triage
