### ISSUE TITLE
radarr add anime support (like sonarr)

### ISSUE THREAD

**Issue by Quafley** [sct/overseerr#3044] opened 2022-09-22 12:38 UTC
### Description

Right now the only possibility is to add movies. I would like to make a suggestion to differentiate between movies and anime movies. This begs the question: is this possible? The reasoning for this is simple. There are people, myself included, who have multiple radarr instances for anime and (normal)movies. I am aware that we can set this up already, my question is if we can make overseerr choose between the 2 instances accordingly and automatically. This makes it so the end-user (when automated) does not need to have access to advanced settings which can mess up a lot of things.

There is currently a feature request #2876 where the request is to remove the requirement for the series to be set up, the comment I left on that post is also my suggestion here.

### Desired Behavior

Overseerr will automatically choose between the two instances. When it's an anime movie, choose instances for anime. When it's a normal movie, choose normal movie instance of radarr.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Quafley** [comment] 2022-11-03 08:07
Any thoughts on this?

**Comment by TheCatLady** [comment] 2022-11-04 03:11
Duplicate of https://github.com/sct/overseerr/issues/1881

**Closed by TheCatLady** 2022-11-04 03:11 UTC
Labels: type:enhancement, awaiting-triage
