### ISSUE TITLE
Requesting a movie does nothing to already added but unmonitored movie

### ISSUE THREAD

**Issue by BodingClockchian** [sct/overseerr#1286] opened 2021-03-25 08:56 UTC
#### Description

Overseerr does not search for an movie when it was already added in radarr (unmonitored or not).
For example I requested the movie Venom. But because it was already unmonitored in radarr it only becomes monitored. But I would like to see a auto search after the 'set to monitor' action.

#### Version
Overseerr: v1.21.1
Radarr: 3.0.2.4552

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Add movie in radarr
2. Set movie to unmonitored
3. Request same movie in overseerr

#### Expected Behavior

Set monitored status + an search 

#### Additional Context

For new (not available) movies this would be fine. But with older movies this is gonna work.

**Comment by samwiseg0** [comment] 2021-03-25 14:46
This is not really a bug. This is by design. 

Can you provide some com context to your use  case? Is there a specific reason you have unmonitored movies that you want users to request? You can just remove the unmonitored movies?

**Comment by BodingClockchian** [comment] 2021-03-25 15:02
Hmm, thats a valid point.
99% of my movies come from multiple trakt lists. A downloaded movie wont be delete from this watchlist. Which means if I do delete the movie in radarr (completely remove it), it will automaticly be added and search for again.
 I haven't found a way to sync radarr and trakt for this 'issue'. Do I have to use the trakt lists? Yes, because of mdblist.com. Movies are automaticly being added.

With for example the movie Venom. I myself watched it like 2 years ago, and deleted the files to safe space. This week someone else would like to watch this movie but is only able to set the status to monitored through overseerr. An extra search action on top of the monitored state would fix this 'issue'.

**Comment by samwiseg0** [comment] 2021-03-25 15:07
> Hmm, thats a valid point.
99% of my movies come from multiple trakt lists. A downloaded movie wont be delete from this watchlist. Which means if I do delete the movie in radarr (completely remove it), it will automaticly be added and search for again.

That is not entirely true... You can have it excluded when you remove the movie so it will not be added by any list automatically. 
![Screen Shot 2021-03-25 at 11 04 09 AM](https://user-images.githubusercontent.com/2241731/112495081-f2cc1980-8d59-11eb-9bbc-368e9a0c7005.png)

> With for example the movie Venom. I myself watched it like 2 years ago, and deleted the files to safe space. This week someone else would like to watch this movie but is only able to set the status to monitored through overseerr. An extra search action on top of the monitored state would fix this 'issue'.

Yes it would just require us to account for that case. I will let @sct weigh in on if he would like to implement this.

**Comment by BodingClockchian** [comment] 2021-03-25 15:43
Oh yes, im aware of that option. But it requires to delete the movie in radarr manually. Click on item, remove, selecte exclusion, delete. Right now im deleting movies with a filebrowser manually or a script that deletes watches by user x or movies that are older than x days. 

Really depends on the 'workflow' I guess.

**Comment by samwiseg0** [comment] 2021-03-25 16:16
> Oh yes, im aware of that option. But it requires to delete the movie in radarr manually. Click on item, remove, selecte exclusion, delete. Right now im deleting movies with a filebrowser manually or a script that deletes watches by user x or movies that are older than x days.

Again not true as you can add things to the exclude list manually.. Have your script add it to the exclude list. 
![Screen Shot 2021-03-25 at 12 15 21 PM](https://user-images.githubusercontent.com/2241731/112506206-e77deb80-8d63-11eb-9a0a-29e9bff47c1a.png)

**Comment by Makifun** [comment] 2021-03-27 17:22
I would just like to say that I would like to +1 this request, I hope it will be implemented. I like to keep track of the "history" of Radarr and Sonarr so I never remove anything from them, I just mark things as unmonitored after it has been removed from Plex.

**Comment by coreyp93** [comment] 2021-04-09 17:50
I also have various trakt lists/personal lists add movies to radarr as unmonitored, and dislike that all unmonitored movies appear as requested in overseerr when i personally use monitored/unmonitored to show which movies im interested in downloading and not just assuming all movies listed in radarr i want (right now). Sonarr seems to follow this on overseerr though, i just looked and unmonitored shows/seasons dont show as requested? so why is it different for radarr? I dont see why unmonitored movies should be shown as requested when unmonitored by definition are movies not being actively searched for on radarr.

**Comment by jonocairns** [comment] 2021-04-10 02:20
Would it be valid on request approval to flip the movie/tv show to monitored if it already existed and was set to not monitored? Otherwise there is a disconnect between the two systems - unless there was another form of communication to mark that this may have been approved but has been explicitly NOT allowed by the Radarr/Sonarr owner. This will potentially be a problem for anyone who already has been running Radarr/Sonarrfor a long time before using Overseerr.

Would it also be valid to trigger a search if the item already exists and is monitored? Or is this effectively marked as done as we've successfully handed off to Radarr/Sonarr? (this is probably not required but worth asking!)

**Comment by hotdog218** [comment] 2021-04-12 20:35
I have a lot of movies that are unmonitored but downloaded and "available" on my server. It would be cool to see an upgrade type of function that, when requested, would re-monitor the movie and search for it. In addition to upgrading the quality, this would be great for broken/corrupted files, or files that are missing subtitles. I can make my own issue for this, but it seems a little applicable to this topic.

**Comment by sct** [comment] 2021-04-13 00:24
> I have a lot of movies that are unmonitored but downloaded and "available" on my server. It would be cool to see an upgrade type of function that, when requested, would re-monitor the movie and search for it. In addition to upgrading the quality, this would be great for broken/corrupted files, or files that are missing subtitles. I can make my own issue for this, but it seems a little applicable to this topic.

Part of what you described will be in the issues system we build.

**Closed** 2021-04-18 10:05 UTC
Labels: type:enhancement

**Comment by coreyp93** [comment] 2021-04-27 12:52
> I also have various trakt lists/personal lists add movies to radarr as unmonitored, and dislike that all unmonitored movies appear as requested in overseerr.
> I personally use monitored/unmonitored to show which movies im _interested_ in downloading, as some i manually search for, and would prefer that overseerr not just assume all movies listed in radarr (monitored or unmonitored) i want (right now).
> Sonarr seems to do what im asking on overseerr though, i just looked and unmonitored shows/seasons dont show as requested? So why is it different for radarr? I dont see why unmonitored movies should be shown as requested when unmonitored by definition are movies not being actively searched for on radarr, and clearly have not been requested either. It adds to confusion for users in not knowing whats actually been 'requested' and being searched for and what is not. And the button to request does not show, so no way for users to make the movie monitored/request.
> 
> I would expect movies which are unmonitored in radarr not to show 'requested' statuses in overseerr, only show requested for monitored movies as well as expect users to be able to request any movie which is unmonitored, making it monitored ready to be searched for.

This fix #1449, didn't address my issue which relates to this. All unmonitored movies in radarr show as requested in overseerr, meaning i cannot click to request the movie in overseerr to activate the search for it. For sonarr this works in overseerr but with radarr it does not. This picture shows what i mean. To me this is a serious issue and means myself and users cannot use overseerr to monitor and search for movies which are unmonitored in radarr of which i have many, added from lists in radarr.

<img width="1920" alt="Overseerr Pic" src="https://user-images.githubusercontent.com/42187797/116240080-541d4900-a75b-11eb-9396-f4f24d55f3bb.png">

**Comment by coreyp93** [comment] 2021-04-28 12:35
@TheCatLady Hey thanks for that. Ive updated overseerr and so far cant get it to work. Being they have already been scanned in the database do i have to delete it and start again? Since its already been processed for me im assuming thats why its not working? Or am i missing something? I tried deleting/re-adding radarr and running syncs and it didnt work.
Thats also made me realise it would be nice to have some backup/restore facility for the db/configuration built in? Mainly for convenience when doing things within overseerr.

**Comment by samwiseg0** [comment] 2021-04-28 12:55
> @TheCatLady Hey thanks for that. Ive updated overseerr and so far cant get it to work. Being they have already been scanned in the database do i have to delete it and start again? Since its already been processed for me im assuming thats why its not working? Or am i missing something? I tried deleting/re-adding radarr and running syncs and it didnt work.
> 
> Thats also made me realise it would be nice to have some backup/restore facility for the db/configuration built in? Mainly for convenience when doing things within overseerr. 

Please do not use issues for support. Please use one of our support methods with discord being preferred.

Thanks
