### ISSUE TITLE
Search filter for media type (movie or tv)

### ISSUE THREAD

**Issue by welcoMattic** [sct/overseerr#2654] opened 2022-03-30 07:20 UTC
### Description

I would like to filter search results to find only movies or only tv shows.

### Desired Behavior

2 checkboxes "Movies" and "TV" aside the search bar to filter search results

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-03-30 13:15
Duplicate of #459

**Closed** 2022-03-30 13:15 UTC
Labels: type:enhancement, awaiting-triage
