### ISSUE TITLE
Add support for postgresql

### ISSUE THREAD

**Issue by onedr0p** [sct/overseerr#3466] opened 2023-05-23 19:21 UTC
### Description

I'd love to be able to connect Overseerr to a Postgres database instead of SQLite

### Desired Behavior

Ideally, I'd like for there to be a set of environment variables that can be set in order to configure and use an external database connection. That way, the default (with no variables set) would be SQLite and no functionality is broken or removed for simple deployments like this. If the user so desires, they would be able to enable and configure the database, significantly expanding deployment options.

### Additional Context

There was previous issue but it looks like the OP got frustrated with the lack of communication on it

https://github.com/sct/overseerr/issues/3176

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-05-24 00:06
Duplicate of #3176

**Comment by onedr0p** [comment] 2023-05-24 01:07
@TheCatLady thanks for reopening that other issue. I figured the op didn't care anymore. Hopefully they don't close it again.

**Comment by TheCatLady** [comment] 2023-05-24 01:08
> @TheCatLady thanks for reopening that other issue. I figured the op didn't care anymore. Hopefully they don't close it again.

No problem!

**Closed** 2023-05-24 07:38 UTC
Labels: type:duplicate
