### ISSUE TITLE
Mark content as "Broken"

### ISSUE THREAD

**Issue by AnysSido** [sct/overseerr#1989] opened 2021-08-14 10:28 UTC
#### Description

Every now and again a broken copy of a movie or tv show is downloaded via automation. It could be unable to play, might have dodgy audio, sometimes even the wrong movie.

#### Desired Behavior

An option for a user to select an item in Overseerr and mark it as "Broken" which would notify the admin.

#### Additional Context

Every so often family members will message me telling me a download is broken for one reason or another. It would be nice if they could do this via Overseerr instead.

**Comment by sct** [comment] 2021-08-14 11:38
Duplicate of #635

**Closed by sct** 2021-08-14 11:38 UTC
Labels: type:enhancement, awaiting-triage
