### ISSUE TITLE
Overseer does not support reverse proxy in subfolders, need to beable to set base url for overseer to support.

### ISSUE THREAD

**Issue by RageInvader** [sct/overseerr#798] opened 2021-01-31 21:15 UTC
Overseer does not support reverse proxy in subfolders, need to be able to set base url for overseer to support.

Running Version 1.18.0

**Comment by samwiseg0** [comment] 2021-01-31 21:27
In the future please fill out the entire template. Dupe of https://github.com/sct/overseerr/issues/274

**Closed by samwiseg0** 2021-01-31 21:27 UTC
Labels: type:duplicate
