### ISSUE TITLE
Default Anime Server

### ISSUE THREAD

**Issue by espentruls** [sct/overseerr#2720] opened 2022-04-26 15:27 UTC
### Description

Would it be possible and easy to implement a toggle to choose Anime as a option when "Adding  A New Sonarr Server".
I know you can choose from Default and 4K -Server now. But it would be nice to have the option in Add New Sonarr Server to choose Anime.
I have a separate instance of Sonarr that explicitly handles Anime, nothing else, but the way Overseer is configured now is not working as I would like.
When I setup an instance in Overseer of only Anime I have to put in settings for ordinary series as well. And when I go to request an anime it chooses the Default Server even if I remove the anime settings completely from that one as I have done. Best way would be to be able to choose Anime Default and then only have to put in settings for anime. And when someone goes to request an anime show Overseer will correctly choose the anime Sonarr instance like the 4k default does. 

### Desired Behavior

Ability to choose Default Anime Server when configuring new Sonarr Server.
Then be able to only fill out relevant anime settings without the need to input ordinary series settings.
When requesting a series it will request it from the Standard server, but when you choose to request an anime it would request it from the Anime  Server. (How it functions now is that it request it from the standard server even if you have removed anime settings all together, and set up a server only for anime)

### Additional Context

![image](https://user-images.githubusercontent.com/3584613/165336270-7c22df0f-114e-497d-8122-9007cfb9d5b1.png)

This is an example of what it would look like if you select it to be anime server

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-04-26 15:37
Duplicate of #1982

**Closed by TheCatLady** 2022-04-26 15:37 UTC
Labels: type:enhancement, awaiting-triage
