### ISSUE TITLE
Don't treat 4K separately

### ISSUE THREAD

**Issue by jyggen** [sct/overseerr#773] opened 2021-01-28 23:12 UTC
**Is your feature request related to a problem? Please describe.**
I don't have a separate instance for 4K but rather get 4K when it's available/worthwhile. The problem right now is that Overseerr's UI treats something as still "requestable" just because it's _only_ available in 4K - which makes people able to request something that they already can happily stream.

Something that's available in 4K vs. 1080p:

![image](https://user-images.githubusercontent.com/264300/106208550-db423b80-61c3-11eb-95ea-15d11bb8ff82.png)
![image](https://user-images.githubusercontent.com/264300/106209221-eea1d680-61c4-11eb-96ea-062e716f3810.png)

This seems to only be the case with TV series however. For movies, if it's available in 4K, it says "Available" instead of "4K Available" and does not let people request it again.

![image](https://user-images.githubusercontent.com/264300/106209358-2ad53700-61c5-11eb-95db-87b201e48d83.png)

**Describe the solution you'd like**
Don't treat 4K separately if there's no 4K server configured since Radarr/Sonarr don't have multi-file support. So even if I wanted people to be able to request 1080p on top of 4K, it wouldn't be possible without a separate instance anyway.

**Additional context**
Screenshots are from Overseer 1.17.2.

**Comment by sct** [comment] 2021-01-28 23:25
This is fixed in `develop` and will be in the next release.

Duplicate of https://github.com/sct/overseerr/issues/695

**Closed by sct** 2021-01-28 23:25 UTC
Labels: awaiting-triage, type:enhancement
