### ISSUE TITLE
Multilingual Support for Discord Notifications

### ISSUE THREAD

**Issue by ninidas** [sct/overseerr#3794] opened 2024-02-23 12:16 UTC
### Description

We can't send notifications in another language than english.

### Desired Behavior

Currently, Overserr sends notifications to Discord only in English, limiting accessibility for non-English speaking users. To enhance user experience and inclusivity, It would be great to implement multilingual support for Discord (and others) notifications. This feature would allow users to receive notifications in their preferred language, making the application more accessible to a global audience. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment] 2024-02-23 18:30
Duplicate of #3624.

**Closed by OwsleyJr** 2024-02-23 18:30 UTC
Labels: type:enhancement, awaiting-triage
