### ISSUE TITLE
Support for Anime only Sonarr/Radarr instances :Enhancement request:

### ISSUE THREAD

**Issue by Kha-kis** [sct/overseerr#1982] opened 2021-08-13 00:43 UTC
Currently Overseerr is able to support a dedicated 4K sonarr/radarr instance.
 On top of my 4K instances I also run instances of sonarr/radarr for anime.

These are setup with different release profiles.
https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx-Anime/ Is a popular example of this and the use case for the separate instance. 

In order to ensure that I am able to obtain the anime release that I am looking for having overseerr the capability to distinguish if a show is classified as anime or not and able to route to the correct sonarr/radarr instance would be extremely useful.

I believe this would also help solve issue [#1881](https://github.com/sct/overseerr/issues/1881)
And issue [1943](https://github.com/sct/overseerr/issues/1943)

Thanks for all of the great work on overseer thus far!

**Comment by sct** [comment] 2021-08-13 00:49
This is a duplicate of #1881 though because our request routing feature will allow you to route any requests to any server under almost any condition. Keep track of that issue for updates.

**Closed by sct** 2021-08-13 00:49 UTC
