### ISSUE TITLE
Multiple BOT Discord

### ISSUE THREAD

**Issue by WoisWoi** [sct/overseerr#2507] opened 2022-02-05 20:38 UTC
### Description

Allow the use of multiple Discord bot, to refine and customize the use of notifications.

### Desired Behavior

Well, I think the description is straight forward. The purpose of this idea is to be able to send different types of notifications in different channels.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-02-05 21:52
Duplicate of #1664

**Closed** 2022-02-05 21:52 UTC
Labels: type:enhancement, awaiting-triage

**Comment by WoisWoi** [comment] 2022-02-05 21:54
My bad, (I forgot) I saw it last year... I thought the need had changed with the issue system :)
