### ISSUE TITLE
Option to request both 4k and 1080p at the same time by default

### ISSUE THREAD

**Issue by asherbig** [sct/overseerr#3107] opened 2022-11-04 02:49 UTC
### Description

Hey! I have a lot of users that request various movies, and I would like to keep my 4k library and my 1080p library the same. But people have been requesting movies in 1080p and other movies in 4k.

### Desired Behavior

There could be a setting to enable the this behavior:

When my users request a movie, I'd like it to send the request to both the 1080p Sonarr/Radarr and the 4k Sonarr/Radarr. The option to request specifically 1080p or 4k would no longer be present. In request approvals, I would still want the ability to not grab 1080p/4k based on my own discretion.

At the very least, I think that there should be an option for: requesting 4k automatically requests in 1080p. Although the above explanation would be exactly what I want.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-11-04 05:25
Duplicate of #2775

**Closed** 2022-11-04 05:25 UTC
Labels: type:enhancement, awaiting-triage
