### ISSUE TITLE
Allow users to 'register interest' in something already requested

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#3162] opened 2022-12-14 02:13 UTC
### Description

Often times, when one person wants to request something, others want it to.  It would be cool if a user could register interest in an already requested item, so that when it is available they get notified too as if they had requested it as well.

### Desired Behavior

Notify all interested parties when an item is available, regardless of whether they were the original requestor.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-12-14 02:33
Duplicate of #789

**Closed by TheCatLady** 2022-12-14 02:33 UTC
Labels: type:enhancement, awaiting-triage
