### ISSUE TITLE
Newsletter containing all "recently added" sent to users on a schedule

### ISSUE THREAD

**Issue by rmeaux** [sct/overseerr#1583] opened 2021-05-06 06:05 UTC
#### Description

A newsletter that goes out daily, weekly, bi-weekly, or monthly to owner/users that list the media that was added to Plex since the last newsletter. 

#### Desired Behavior

Add a newsletter tab in "Notifications" that can enable a newsletter being sent. Have selection options for the frequency and time this should be sent. Under each users permissions add a switch if they should receive this newsletter. Newsletter would contain the titles and posters of movies added and the series title, episodes, and posters of TV Shows added since the last newsletter was mailed out. 

#### Additional Context

This is the only missing feature that is keeping running a similar docker along side this one.

**Comment by TheCatLady** [comment] 2021-05-06 06:09
Duplicate of #645, which was closed since this functionality already exists in Tautulli.

**Closed by TheCatLady** 2021-05-06 06:09 UTC
Labels: awaiting-triage, type:enhancement

**Comment by rmeaux** [comment] 2021-05-06 15:08
Thanks. I'll look into that. You taught me something today. I tried to look for a duplicate before I posted but must have missed it. Thanks again.
