### ISSUE TITLE
FR - Ability to specify different discord webhooks.

### ISSUE THREAD

**Issue by fscorrupt** [sct/overseerr#3048] opened 2022-09-25 07:45 UTC
### Description

I would love to be able to seperate the Discord Notifications in seperate channels with different webhook urls.

### Desired Behavior

One webhook/channel for requests
second webhook/channel for issues
third webhook/channel for available requests and and and.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-09-25 20:45
Duplicate of #1664

**Closed** 2022-09-25 20:45 UTC
Labels: type:enhancement, awaiting-triage
