### ISSUE TITLE
Search not triggered adding older seasons of existing show

### ISSUE THREAD

**Issue by veritas2884** [sct/overseerr#1132] opened 2021-03-09 15:07 UTC
If SONARR already has a show with some, but not all, seasons loaded and a user requests an older season, SONARR will mark the season wanted but not trigger a forced search. Since these are obviously older episodes now, there is a very small chance they'll appear on an RSS feed and will require a full search to source an episode.

Example: SONARR has Seasons 1 & 2 of The Sopranos. User requests Season 3. Season 3 flipped to wanted but not searched for. The request will never be fulfilled unless manual intervention is taken.

This is a small issue and just wanted to give a heads up. Love the software and very grateful for you making it.

**Comment by sct** [comment] 2021-03-09 15:09
Duplicate of #588

**Comment by samwiseg0** [comment] 2021-03-09 15:09
This is a dupe of #588 as well.

**Closed** 2021-03-09 15:09 UTC
Labels: invalid:template-incomplete
