### ISSUE TITLE
Ability or option to notify with each season availability.

### ISSUE THREAD

**Issue by natebur** [sct/overseerr#2097] opened 2021-09-17 11:17 UTC
I skimmed through the current requests and didn’t see this. 

I think it would be helpful for overseerr to notify the requesters when a season of a show is available. I know when Netflix drops a season and it gets added that should notify as nothing else beyond is available. But I was mainly thinking when someone requests a 10-20 year or more old show. Sometimes it can take time to find all the episodes. And if they could get notified that 1-6 were available, they could start watching those while I continue to search

**Comment by samwiseg0** [comment] 2021-09-17 11:21
Duplicate of https://github.com/sct/overseerr/issues/789.

**Closed by samwiseg0** 2021-09-17 11:21 UTC

**Comment by natebur** [comment] 2021-09-17 12:02
I don’t think this exactly like the linked issue. I was meaning the default notifications when the whole series is available, also have it notify for each season of that series.

**Comment by samwiseg0** [comment] 2021-09-17 13:45
> I don’t think this exactly like the linked issue. I was meaning the default notifications when the whole series is available, also have it notify for each season of that series.

Understood, I do not believe this should be the default behavior. If a user wanted this type of notification they can do it today by requesting each season individually. Secondly, the linked issue can apply in this scenario as they could subscribe to the other seasons they requested to be notified individually. I understand it’s not a perfect fit but I believe the linked feature would cover this use case. I could see where the user could have a setting in their profile for this behavior that they could enable but I still believe this would fall under the linked issue. I suggest you leave a comment on that issue with the functionally you desire and we can always break it out into a separate feature if the developers decide to go a different route. 

Thanks for the suggestion!
