### ISSUE TITLE
Filter: Processing and released

### ISSUE THREAD

**Issue by scallister** [sct/overseerr#1294] opened 2021-03-25 21:26 UTC
#### Description

I'd like a new filter to show requests that released and processing. When looking for requests that may have become stuck, I'm not interested in requests that are in processing but have not yet been released.

#### Desired Behavior

A new option on the requests page for "Processing and released" (or another name that serves this purpose)

**Comment by TheCatLady** [comment] 2021-03-26 12:02
Duplicate of #1181

**Closed by TheCatLady** 2021-03-26 12:02 UTC
Labels: awaiting-triage, type:enhancement
