### ISSUE TITLE
Add Anime Movies for Radarr

### ISSUE THREAD

**Issue by NepBlanc** [sct/overseerr#2891] opened 2022-08-06 10:59 UTC
### Description

Add a part just like Sonarr that allows for anime movies.

### Desired Behavior

The automation in sonarr is very useful so I'd like the same functionality for movies as well.
So that my users that want to add anime movies, don't have to select the right profile.
Just directly download it in the right folder and plex library, as sonarr does.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-08-16 16:12
Duplicate of #1881

**Closed by TheCatLady** 2022-08-16 16:12 UTC
Labels: type:enhancement, awaiting-triage
