### ISSUE TITLE
Multiple Plex Server Support

### ISSUE THREAD

**Issue by tahmidul612** [sct/overseerr#2310] opened 2021-11-27 02:00 UTC
### Description

I have two plex servers running at different locations. But overseerr can only check for content availability for one server.

### Desired Behavior

I would like to have overseerr be able to check multiple plex servers for content availability, and have the "play on plex" link direct the user to the server the content is in.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-11-27 03:54
Duplicate of #1094

**Closed** 2021-11-27 03:54 UTC
Labels: type:enhancement, awaiting-triage
