### ISSUE TITLE
Request availability status bug

### ISSUE THREAD

**Issue by anonyme123** [sct/overseerr#3081] opened 2022-10-16 22:22 UTC
### Description

When a request is marked as available, and if the show is then deleted from Plex, the availability status of the request doesn't change.

### Version

1.30.1

### Steps to Reproduce

1. Request a show 
2. Let the request fulfill. The request status changes to 'available'
4. Delete the show from Plex. The request in Overseerr is still 'available'

### Platform

desktop

### Device

Linux Server

### Operating System

Ubuntu 20.04.5 LTS (GNU/Linux 3.10.0-1160.11.1.el7.x86_64 x86_64)

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment] 2022-10-16 23:12
This is being worked on in #2890 and is a duplicate of #377

**Closed by sct** 2022-10-16 23:12 UTC
Labels: type:bug, awaiting-triage
