### ISSUE TITLE
Add possibility to fix a data limit

### ISSUE THREAD

**Issue by AthAshino** [sct/overseerr#1665] opened 2021-05-18 11:40 UTC
#### Description

Actually I own a NAS with 6To free. Every user can ask 20 movies and 2 tvshow per week. The problem is that not every movie/tvshow has same data weight and they will not impact the server the same way

#### Desired Behavior

A good thing would be to create a data limit per user based.
Example : I have a 100Go limit, I ask GoT S01-07, it is 300Go, I can't ask anything else (movie/tvshow) until the end of the cycle

**Comment by sct** [comment] 2021-05-18 11:42
Duplicate of #1539

**Closed by sct** 2021-05-18 11:42 UTC
Labels: awaiting-triage, type:enhancement
