### ISSUE TITLE
Report issues with available media

### ISSUE THREAD

**Issue by rub1xcub3** [sct/overseerr#2120] opened 2021-09-23 03:18 UTC
#### Description
There are many instances where media may have muffled sound, or is perhaps I'm the wrong language. I would like for there to be a way users can mark it as a problem, or to re-download, etc.
#### Desired Behavior
Users can mark media as not working, I as the admin can acknowledge the issue, and then mark it as resolved when completed. User can then get a notification for the respective status.

Provide a clear and concise description of what you want to happen.

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by samwiseg0** [comment] 2021-09-23 03:28
duplicate of https://github.com/sct/overseerr/issues/635

**Closed by samwiseg0** 2021-09-23 03:28 UTC
Labels: type:duplicate
