### ISSUE TITLE
Filter by Movie or Series for 'Trending'

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#3101] opened 2022-10-30 21:44 UTC
### Description

Sometimes I just want to see trending movies or trending series

### Desired Behavior

allow seeing both, or split it out, like is done for 'upcoming'

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-10-31 17:06
Duplicate of #459

**Closed by TheCatLady** 2022-10-31 17:06 UTC
Labels: type:enhancement, awaiting-triage
