### ISSUE TITLE
See missing episodes not just "Partially Available"

### ISSUE THREAD

**Issue by ZerkerEOD** [sct/overseerr#3666] opened 2023-11-03 16:03 UTC
### Description

I would like to see which episodes are missing from a series. This would be useful for people I share my library with and give access to overseerr the ability to look up a series that I have and they want to watch to make sure I have enough of it for them to start or watch through. 

### Desired Behavior

Under a series when it says partially available, have a bar on each episode that says if it is available. This could help end users decide to watch a series or not.,

### Additional Context

This is purely a GUI enhancement to help end-users that have access to someone's shared libraries without having access to the arr's to view if the series is missing a single episode that isn't out yet or missing 90% of the season without having to reach out or manually look at plex and compare how many episodes the season should have.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment] 2023-11-03 16:18
Duplicate of #342.

**Closed by OwsleyJr** 2023-11-03 16:18 UTC
Labels: type:enhancement, awaiting-triage

**Comment by ZerkerEOD** [comment] 2023-11-03 16:24
@OwsleyJr, I saw that post but it's about being able to request specific episodes not viewing episodes. How is the logic done to determine if the season is fully available vs partially available unless you are seeing the status of each episode?

**Comment by OwsleyJr** [comment] 2023-11-03 16:33
> @OwsleyJr, I saw that post but it's about being able to request specific episodes not viewing episodes. How is the logic done to determine if the season is fully available vs partially available unless you are seeing the status of each episode?

We check the total amount of episodes in the show vs how many you have available. We do not have individual episode support at all right now.

So your request + issue #342 kinda go hand in hand.

**Comment by ZerkerEOD** [comment] 2023-11-03 20:36
@OwsleyJr ahh that makes sense, thanks for clarifying
