### ISSUE TITLE
Notify with message on delete

### ISSUE THREAD

**Issue by scallister** [sct/overseerr#2520] opened 2022-02-07 21:41 UTC
### Description

Sometimes I need to go delete requests that are just simply not going to be fulfilled for one reason or another, for example the request is for something way too rare.

When I delete the request there is no notification e-mail sent to the user.

### Desired Behavior

I'd like the delete request button to pop up with a dialog for adding a quick message to the user. If I don't fill out the dialog, a generic "your request has been deleted" message could be sent. If I do fill out the dialogue, the deleted request message could say something like "your request has been deleted for reason: <reason that I provided>"

IE:
```
Your request has been deleted for reason: This item is too rare, sorry John
```

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-02-07 23:32
Duplicate of #572 and #593

**Closed** 2022-02-07 23:33 UTC
Labels: type:duplicate
