### ISSUE TITLE
UX - Confusing end-user experience with current behaviour of "Partially available" and "Available" labels on TV Shows.

### ISSUE THREAD

**Issue by Drapersniper** [sct/overseerr#2258] opened 2021-11-03 15:18 UTC
### Description

I'm aware of https://github.com/sct/overseerr/issues/1477, but I didn't want to necro an old post (sorry if you'd prefer if I had commented there) 

I've added some screenshots to try to describe it better.

The issue here is that continuing series is most of the time shown as "partially available" in the labels however this is not the case for every show., for example in American Horror Story.

While I do understand your point in issue #1477 ,  one could argue that the context matter as a series without an aired episode could and should be treated as completed until there is an aired episode that has not been acquired.

I'm a new Overseer user and I'm absolutely loving it please don't think I'm just trying to point out issues, it was one of my users who flagged to me that they were going to wait for their requested series to be available before they would watch it but I knew all the content had been acquired already.

It's not clear to the end-user that all aired content is available, and even in cases where "available" does show as you'd expect by using the logic stated in #1477 it means it should be "Partially Available".

### Desired Behavior

Sonarr does already expose all the required info for the status of a given series it would be great if we would match it to the service being used., if this is completely out of the question then we should ensure that "partially available" is shown to all continuing shows and not just some of them.

On #1477 you mention #342, so perhaps your intent is that when per episode functionality is added we will show a "Partially available X episodes out of x aired"?

### Additional Context

![image](https://user-images.githubusercontent.com/27962761/140085609-d697ccd0-79c0-4ed3-b18f-174b7c356cf6.png)
![image](https://user-images.githubusercontent.com/27962761/140085721-7997c804-faef-4790-bad3-e09b9c785e75.png)

![image](https://user-images.githubusercontent.com/27962761/140086394-16aac282-d5f0-4d6d-a2bb-f2f4a6fae637.png)
![image](https://user-images.githubusercontent.com/27962761/140086196-fdabb5e4-5582-46fd-a0d2-f645a67720c4.png)

![image](https://user-images.githubusercontent.com/27962761/140087029-5dae86bb-4adc-4d0f-8268-41f5995886e4.png)
![image](https://user-images.githubusercontent.com/27962761/140086687-f534e83a-9a70-49ce-a40a-7ab292d8efb9.png)
[Imdb's entry](https://www.imdb.com/title/tt1844624/) for American Horror story
![image](https://user-images.githubusercontent.com/27962761/140086806-465be996-48f5-40f7-a1e1-b56ba4651f85.png)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-11-03 15:25
Duplicate of #1477

Please see the comment from @sct on #1477.

**Closed by TheCatLady** 2021-11-03 15:25 UTC
Labels: type:enhancement, awaiting-triage

**Comment by Drapersniper** [comment] 2021-11-03 15:28
Hi I did read it, but it didn't address the inconsistent usage of the "available" label.

**Comment by TheCatLady** [comment] 2021-11-03 15:31
@Drapersniper The "Available" label is applied to series for which all known episodes (based on TMDb data) are available.  The Overseerr behavior is consistent, but the TMDb data we depend on may not be perfect.

**Comment by Drapersniper** [comment] 2021-11-03 15:36
I appreciate that, but when the backend which is required by overseer (sonarr in this case) provides you with more accurate information wouldn't it make sense to use it ? To avoid confusion to the end users? It just feels like you are shutting down the suggestion with any explanation as to why not use the more accurate data, perhaps there is some edge cases that I'm not taking into consideration?

Accurate as in a continuing series have no episode left that hasn't been aired is flagged as complete by the Sonarr.

**Comment by TheCatLady** [comment] 2021-11-03 15:52
Overseerr does not query Sonarr in every place that we display the media status.  The media status is our best approximation of the status based on Plex & Sonarr scans.  And unfortunately, Sonarr uses TVDB data while Overseerr is powered by TMDb.

As @sct has previously stated, things should be a lot more clear.  However, there are no changes planned for statuses at this time.
