### ISSUE TITLE
Show movies for each network

### ISSUE THREAD

**Issue by r4f4w** [sct/overseerr#2836] opened 2022-06-26 13:50 UTC
### Description

Today, when you select to see content from a network, it only show series and not movies. There should be a way to be able to filter movies from each network. Maybe show in the same place with series, or maybe create a filter whitin.

### Desired Behavior

Show movies **and** series for each network.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-06-26 18:51
Duplicate of #2668

**Closed by TheCatLady** 2022-06-26 18:51 UTC
Labels: type:enhancement, awaiting-triage
