### ISSUE TITLE
Add request to more than one Radarr instance simultaneously.

### ISSUE THREAD

**Issue by stephan2006** [sct/overseerr#3074] opened 2022-10-15 02:56 UTC
### Description

**Request**
Would like to be able to have a request be sent to more than one Radarr instance at the same time. Possibly based on move release status.

### Desired Behavior

**My Use Case**
I have 3 instances of Radarr running, 1 for 4K Movies, 1 for General Movies, and 1 for Pre-Release Movies. It would be nice if when someone add a movie that is upcoming, it could be added to both the Pre-Release and the Either the general or the 4K Radarr depending on what was requested.

**Other Use Case**
Adding a request to both an HD and a 4K instance if you wanted to maintain a separate library.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2022-10-15 03:30
Duplicate of #2775.

Also, [Syncarr](https://github.com/syncarr/syncarr) might be of interest to you.

**Closed by danshilm** 2022-10-15 03:30 UTC
Labels: type:enhancement, awaiting-triage
