### ISSUE TITLE
Ability to un-approve/remove a request and notify user as to the reason

### ISSUE THREAD

**Issue by hansenc0705** [sct/overseerr#2623] opened 2022-03-14 20:14 UTC
### Description

Sometimes content is either auto or manually approve that is unable to be found. It would be nice to be able to easily communicate this to users somehow when removing the request from Overseerr.

### Desired Behavior

A method to remove/un-approve a media request with a prompt that allows you to either select a reason why or provide a freeform text box to provide a reason.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-03-14 20:18
Duplicate of #572

**Closed by TheCatLady** 2022-03-14 20:18 UTC
Labels: type:enhancement, awaiting-triage
