### ISSUE TITLE
Ability to exclude networks from lists like "trending"

### ISSUE THREAD

**Issue by phil164** [sct/overseerr#2267] opened 2021-11-06 16:41 UTC
### Description

It would be a nice to have function to exclude some networks from the results presented to the user, if he has (for example) a netflix subscription.

Maybe a dropdown in the user settings menu to untick networks, so they don't show up in trending or general search.

### Desired Behavior

Go to User settings.
Untick a network in a dropdown of all networks.
Don't get search results from this network.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment] 2021-11-06 17:38
Duplicate of https://github.com/sct/overseerr/issues/1239 and https://github.com/sct/overseerr/issues/1340

**Closed by samwiseg0** 2021-11-06 17:38 UTC
Labels: type:duplicate
