### ISSUE TITLE
Media availability status change not detected (radarr)

### ISSUE THREAD

**Issue by iamwoz** [sct/overseerr#1831] opened 2021-06-23 02:35 UTC
1. Radarr pulled a bad version of A Quiet Place II
2. Overseer updated to Available
3. I used Radarr to delete the media file
4. Overseer rescans and doesn't see any change (full log attached):

2021-06-22T16:05:51.506Z [debug][Radarr Scan]: Title already exists and no changes detected for A Quiet Place Part II

The directory for this media file doesn't even exist in the filesystem and Radarr knows there is no file downloaded and notes it as missing:

![image](https://user-images.githubusercontent.com/85816876/123026186-dbbbc700-d42f-11eb-9037-1b85bbe30bfa.png)

Overseer believes otherwise (even after full rescan):

![image](https://user-images.githubusercontent.com/85816876/123026238-efffc400-d42f-11eb-925d-d96877403ca7.png)

![image](https://user-images.githubusercontent.com/85816876/123026271-fc841c80-d42f-11eb-8f0c-63567a93cf32.png)

Overseer is running in a docker container from ghcr.io/linuxserver/overseerr:develop on UnRaid 6.9.2

Chrome 91.0.4472.114 64bit on Windows 10 21H1 19043.1052

Cheers, Woz.

[overseerr.log](https://github.com/sct/overseerr/files/6698486/overseerr.log)

**Comment by Drawmonster** [comment] 2021-06-23 03:01
This looks like a duplicate of #377 .

**Comment by samwiseg0** [comment] 2021-06-23 03:08
Something you have in Plex is matching this ID or it matched at some point. This is not a bug. If the media was deleted then it relates to #377

**Closed** 2021-06-23 03:09 UTC
Labels: support
