### ISSUE TITLE
Feature Request: Default Anime Server setting

### ISSUE THREAD

**Issue by jjjonesjr33** [sct/overseerr#2539] opened 2022-02-12 01:55 UTC
### Description

Requesting that the option to have a seperate anime sonar instance without being forced to have a default tv sonarr instance in the settings would be nice. 

I run multiple containers. One for tv shows, one for 4k tv shows, and one for anime. The way that it is programmed now forces my tv show container to be used for anime as the default server request without manually changing it.

![image](https://user-images.githubusercontent.com/29973406/153691839-28752c21-61b8-4fa2-88e9-72ac6fe134e4.png)

### Desired Behavior

Just like how it is already setup to do a default server for the main server and a 4k server. 

Add in the option to have a default anime server.
![image](https://user-images.githubusercontent.com/29973406/153691682-c9b786a9-8522-4bf7-90fa-00e23d15837c.png)
And remove the requirements for quality tv settings
![image](https://user-images.githubusercontent.com/29973406/153691742-abc199e2-4e2f-452e-a67d-04d2dccb19d5.png)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-02-12 01:57
Duplicate of #1881

**Closed by TheCatLady** 2022-02-12 01:57 UTC
Labels: type:enhancement, awaiting-triage

**Comment by jjjonesjr33** [comment] 2022-02-12 01:59
> Duplicate of #1881

The request he has is in regards to radarr not sonarr.

**Comment by p5nbTgip0r** [comment] 2022-03-04 19:28
> The request he has is in regards to radarr not sonarr.

What I described in the issue isn't going to be the solution anymore, as the issue was changed to be about request routing. I'll work on changing it later when I have time. From what was said, I believe request routing will work similarly to [Petio's filter system](https://docs.petio.tv/configuration/filters) where you can modify which server a request gets sent to depending on whatever criteria you set for each request.

In your case, an example of handling it would be: 
`{TMDb Keywords}` contains `anime` ([which is how overseerr tells if a show is anime](https://github.com/sct/overseerr/blob/822ae9eec711a92b61c8ea5bd7b157aee7d601f7/src/components/RequestModal/TvRequestModal.tsx#L704-L706))
then `{your anime sonarr instance}`.. or something similar to that.
