### ISSUE TITLE
Add ability to select language profile for users

### ISSUE THREAD

**Issue by V-ed** [sct/overseerr#2350] opened 2021-12-15 20:25 UTC
### Description

It would be useful to have a way to set the language profile for a particular user (not the Overseerr display language, but rather the language profile used for Radarr/Sonarr when requesting content).

The use case is that by default, every requests are in English, but I know a user's English ability to not be great and that user would prefer to search in French by default.

### Desired Behavior

Adding a language selector for each user to properly send requests to Radarr / Sonarr, using the profile selected.

Radarr would need to select the proper Quality Profile :
![image](https://user-images.githubusercontent.com/16652915/146258244-98fb289c-99b7-41f6-a01e-12bea5273787.png)

While Sonarr would need to use the proper Language Profile :
![image](https://user-images.githubusercontent.com/16652915/146258358-0a566c95-2513-4622-955e-7f918d179286.png)

### Additional Context

This feature already exists in Ombi :

![image](https://user-images.githubusercontent.com/16652915/146259564-03afded0-dd3e-407b-9e3a-744a114604d2.png)

The image above is an example of a user's configuration as described by the use case given.
This is configurable per user in Ombi, which I find very useful, as I could even make root folders for every user if I may choose (my user pool is tightly controlled).

Coming from Ombi, I really like the experience so far, thanks for this amazing software!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-12-15 20:31
Duplicate of #609

**Closed by TheCatLady** 2021-12-15 20:31 UTC
Labels: type:enhancement, awaiting-triage

**Comment by V-ed** [comment] 2021-12-15 20:34
> Duplicate of #609

While I agree that parts of my feature request mentions paths by user, mine is more specifically about the language profile.

Is the language profile also part of the scope of the issue you linked, @TheCatLady?
