### ISSUE TITLE
Ability to request a season of an already partially available season

### ISSUE THREAD

**Issue by skos-ninja** [sct/overseerr#1098] opened 2021-03-05 14:05 UTC
#### Description

Trying to request a season of an already partially available season isn't possible if episodes exist for it even when Sonarr isn't set to monitor that season.

#### Desired Behavior

Ideally you should be able to always request a season of a series unless it is all available and/or already monitored in Sonarr.

**Comment by TheCatLady** [comment] 2021-03-05 14:16
Duplicate of #349

**Closed** 2021-03-05 14:29 UTC
Labels: type:duplicate
