### ISSUE TITLE
Ability to have multiple libraries

### ISSUE THREAD

**Issue by dextercf** [sct/overseerr#540] opened 2020-12-31 09:57 UTC
**Is your feature request related to a problem? Please describe.**
When approving request the movie/series is added to to first library of that type and I have to manually move the files to another library after transfer.

**Describe the solution you'd like**
When users add requests have them provide which library is most fittet for the content.
While approving requests it should be possible to choose which library the content should be added to.

**Describe alternatives you've considered**
As of now I have yet to consider any other solution than to manually move the content after download.

**Additional context**
I have my plex separated into libraries for children and libraries for adults.
This so that the kids don't have to see the horror movies.
With how it is now everything gets added to the adult libraries and need to be manually moved over to the childrens libraries.

**Comment by samwiseg0** [comment] 2020-12-31 13:35
Dupe of https://github.com/sct/overseerr/issues/351

**Closed by samwiseg0** 2020-12-31 13:35 UTC
Labels: awaiting-triage, type:enhancement
