### ISSUE TITLE
Add more filter options/tab to the requests page

### ISSUE THREAD

**Issue by NoMorePeace** [sct/overseerr#1721] opened 2021-06-01 05:34 UTC
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'm looking for a way to filter request to show only TV Shows for one of my admins and Movies for another admin.
Maybe having a Tab under the Requests text to switch between TV Shows, Movies, or Anime.
Or add another drop down menus for content type.

Would be amazing if we have an option to set the default Sonarr for Anime and one for TV Shows just like 4k.

**Describe alternatives you've considered**

None so far.

**Comment by samwiseg0** [comment] 2021-06-01 05:35
Duplicate of https://github.com/sct/overseerr/issues/1181

**Closed** 2021-06-01 05:36 UTC
Labels: type:duplicate
