### ISSUE TITLE
Add custom folder routing based on tvdb/tmdb tag

### ISSUE THREAD

**Issue by fwicht** [sct/overseerr#2330] opened 2021-12-08 17:21 UTC
### Description

Much like the anime folder routing that is based on the `anime` tag, this would be nice to add custom folder routing based on tvdb or tmdb tag. 

Users could add specific mappings by editing the service in question.

For example, based on tvdb tag `documentary` one user would maybe want to map this type of requests to folder `/docs`.

### Desired Behavior

Being able to add/edit folder mappings under the desired service for certain types of tags.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-12-08 17:23
Duplicate of #1881

**Closed by TheCatLady** 2021-12-08 17:23 UTC
Labels: type:enhancement, awaiting-triage
