### ISSUE TITLE
Sorting for Search results?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [sct/overseerr#1654] opened 2021-05-17 19:13 UTC
#### Description

When doing a search, it would be easier if items already available appear separately from non-available.

#### Desired Behavior

Currently, there is a small green check, which is  useful, but it would help to add  some separation between the two.

For example, I currently have 3 Porky's movies on my Plex, and doing a search for "Porky", shows this (is it real simple to tell what's available already?):

![image](https://user-images.githubusercontent.com/39491297/118543379-d45f1a80-b719-11eb-9d6d-5ffd0f1984f1.png)

If the available showed up as the first line(s), followed by a gap/space, and then the unavailable, it would solve the issue.  :)

P.S. Also perhaps separate out the movies from the series as well.

**Comment by samwiseg0** [comment] 2021-05-17 19:15
Duplicate of https://github.com/sct/overseerr/issues/459

**Closed** 2021-05-17 19:16 UTC
Labels: type:duplicate

**Comment by YouveGotMeowxy** [comment] 2021-05-17 19:20
@samwiseg0 Not a dupe of that, but I can see how you'd want to just group it in with all those others, for organization. :)

**Comment by samwiseg0** [comment] 2021-05-17 19:21
Yes you are correct. As the idea is unique it would fall under that feature. We would just have an option to filter the requests as you outlined. Thanks for great idea!
