### ISSUE TITLE
[Feature] Allow setting tags when requesting 

### ISSUE THREAD

**Issue by DevYukine** [sct/overseerr#1289] opened 2021-03-25 18:47 UTC
#### Description

I would like to be able to apply tags based on show type (Anime or Series) or maybe even when requesting so i can guarantee which terms (groups) are allowed, i currently use that heavily for anime since i only want specific sub groups used

#### Desired Behavior

i think i already explained it very well, it could be implemented in different ways, based on show type or maybe even user can specify them or admin can set presets or simular i don't mind either tbh

**Comment by samwiseg0** [comment] 2021-03-25 19:14
Dupe of https://github.com/sct/overseerr/issues/290

**Closed by samwiseg0** 2021-03-25 19:14 UTC
Labels: type:duplicate
