### ISSUE TITLE
On ios/safari- can't 'break out' of overseer screen

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#3103] opened 2022-10-30 21:48 UTC
### Description

When looking at overseer in safari on ios, you can't change the url to go somewhere else.  just stays in overseer for some reason.

Reported it here - and somebody else confirmed it.  
https://www.reddit.com/r/Overseerr/comments/xqbpsf/overseerr_in_safari_on_ios_cant_leave_site/

### Version

1.30.1

### Steps to Reproduce

Use overseer from safari on ios
Attempt to change your url

### Platform

smartphone

### Device

Iphone 13

### Operating System

ios 16

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-10-31 18:53
Duplicate of #1729

**Closed by TheCatLady** 2022-10-31 18:53 UTC
Labels: type:bug, awaiting-triage
