### ISSUE TITLE
Able to select different quality/language profiles for a request

### ISSUE THREAD

**Issue by Flight777** [sct/overseerr#631] opened 2021-01-11 21:19 UTC
**Is your feature request related to a problem? Please describe.**
I'm in a mixed English/Chinese environment, so I have multiple Radarr profiles for both quality (1080p/4k) as well as Language (English/Chinese). Now I'm only able to use one profile in Overseerr. Which will of course not work well with Chinese movies as well as the 1080p/4k selection.

**Describe the solution you'd like**
Either:
- Users can directly select between multiple profiles (pre-selected by admin based on right)
- Admin can change the profile of the request before approving
- Best: Ruling based on origina language of movie to see if profile is available

**Describe alternatives you've considered**
- Manually adjust in Radarr

**Additional context**
Pretty clear I think. But thanks for the amazing work on this so far 👍

**Comment by danshilm** [comment] 2021-01-11 21:22
#351 would satisfy this.
I like `Ruling based on origina language of movie to see if profile is available` but unsure of how it would work out.

**Comment by sct** [comment] 2021-01-11 22:48
Duplicate of #351

**Closed** 2021-01-11 22:48 UTC
Labels: type:duplicate
