### ISSUE TITLE
Users report faulty titles

### ISSUE THREAD

**Issue by krisnyse** [sct/overseerr#2352] opened 2021-12-17 19:07 UTC
### Description

It would be nice if users could report problems with avaliable titles in the collection so the admin can fix it. 

### Desired Behavior

User reports faulty title. Title appears under under "reported problems" only visible for admin. Admin finds a solution. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-12-17 19:31
Duplicate of #635

**Closed** 2021-12-17 19:31 UTC
Labels: type:duplicate
