### ISSUE TITLE
Complete TV show showing as “Partially Available”

### ISSUE THREAD

**Issue by HubDuck** [sct/overseerr#723] opened 2021-01-22 15:27 UTC
**Describe the bug**
A completed TV show shows up as “Partially Available”, if the TV show contains an episodes which are contained in one file.

Example: Pilot is split over two episodes in TVDB and Sonarr. There is one file called "TV show S01E01-E02".

**What version of Overseerr are you running?**
develop-5e352c201fc2f731ca5f713ecb6901527ef354da

**To Reproduce**

1. Take any TV show in your library that has two or more episodes put into a single file.
1.a. If not available delete (make a backup of) the 2nd episode of any TV show and rename the 1st episode by adding '-E02' behind 'S01E01'.
2. Have Plex scan the show, make sure both episodes show up.
3. Check Sonarr that show is complete.
4. Full Plex sync within Overseerr.
5. Check the label of the show, It should have changed from “Available” to “Partially Available”.

**Expected behavior**
If Sonarr has the TV show down as complete with all episodes, so should Overseerr.

**Comment by sct** [comment] 2021-01-22 16:08
In the rare case this happens, would https://github.com/sct/overseerr/issues/672 be good enough to solve this?

**Comment by HubDuck** [comment] 2021-01-22 16:13
I did look at #672, but opened a new issue because it happens not rarely but quite often I'm afraid.

Checked my library and there are a lot of cases. Ended and continuing shows alike.

**Comment by HubDuck** [comment] 2021-01-23 06:48
Checking a few more shows that are complete.

The “Partially Available” also shows, if there are more episodes than https://www.themoviedb.org/ shows. https://thetvdb.com/ has the correct count, so does Sonarr, but Overseerr displays “Partially Available”.

**Comment by HubDuck** [comment] 2021-01-23 19:26
The Sonarr API https://github.com/Sonarr/Sonarr/wiki/Series could be used to check if a show is complete. The API returns the proper episode count and filecount, even if there is an episode S01E01-E02.

**Comment by TheCatLady** [comment] 2021-02-19 08:18
Hi @HubDuck, are you still experiencing this issue?  I was investigating this just now but could no longer repro the problem.  I think it may have been fixed in 9b73423d49e1e799cd82764a9ade8c75d92a28a2.

**Comment by TheCatLady** [comment] 2021-02-19 15:40
Confirmed to be fixed in 9b73423d49e1e799cd82764a9ade8c75d92a28a2.

**Closed by TheCatLady** 2021-02-19 15:40 UTC
Labels: severity:medium, type:bug

**Comment by AchillesPDX** [comment] 2024-01-01 23:50
I realize this was supposed to have been fixed back in 2021, but I'm still seeing the same problem across several of my TV shows. The US Office for example has multiple two-part episodes that increase the file count but don't increase the number of episodes that Overseerr seems to be expecting which causes "Partially Available" to show. Any ideas how to fix this?

**Comment by BlakeGardner** [comment] 2024-08-07 23:41
Echoing @AchillesPDX I am seeing the same thing currently.

**Comment by Joel-Chapman** [comment] 2025-01-11 22:25
Also echoing @AchillesPDX same here with another show Bangkok Hilton (1989)

**Comment by TromboneFreak** [comment] 2025-02-09 21:29
> Also echoing [@AchillesPDX](https://github.com/AchillesPDX) same here with another show Bangkok Hilton (1989)

Same here with a few shows.
