### ISSUE TITLE
Ability to add tags to users, which can be propagated to sonarr/radarr, this can be used for notifications 

### ISSUE THREAD

**Issue by ikbensuper** [sct/overseerr#1390] opened 2021-04-09 20:12 UTC
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

No problem

#### Desired Behavior

A possibility to add tags to users. When their request gets approved, the tag propagates to radarr/sonarr.

#### Additional Context

With this tag you can configure "connect"'s in radarr and sonarr to send notifications throug radarr & sonarr.

**Comment by samwiseg0** [comment] 2021-04-09 20:15
Duplicate of https://github.com/sct/overseerr/issues/290

**Closed** 2021-04-09 20:15 UTC
Labels: type:duplicate
