### ISSUE TITLE
Show individual seasons within a show and individual episodes within each season

### ISSUE THREAD

**Issue by bandgeekbilly824** [sct/overseerr#1760] opened 2021-06-08 18:06 UTC
#### Description

It would be nice to see the individual seasons when you click on a show. Once in a show you click on a season and it would show you the individual episodes with a synopsis of each episode

#### Desired Behavior

This is already in PETIO which my requesters love. When they click on a show they can see each individual season. Once there they can click on a season and it shows them the episodes within that season along with a synopsis. I saw a feature request on having the ability to request individual episodes. Maybe if they could see them this way they could request them individually from there. Thanks and keep up the good work.

#### Additional Context

![image](https://user-images.githubusercontent.com/15660413/121235077-0fa4c300-c85a-11eb-847b-fb8687518c2c.png)
![image](https://user-images.githubusercontent.com/15660413/121235122-21866600-c85a-11eb-9506-9d2c994f3fdf.png)

**Comment by TheCatLady** [comment] 2021-06-08 18:09
Duplicate of #342

The UI for season/episode details will be added when we have individual episode request functionality.

**Closed by TheCatLady** 2021-06-08 18:09 UTC
Labels: awaiting-triage, type:enhancement
