### ISSUE TITLE
Custom names for Radarr and Sonarr Servers

### ISSUE THREAD

**Issue by ByCreating** [sct/overseerr#1997] opened 2021-08-16 09:46 UTC
#### Description
I am using Overseerr in connection with two Radarr and Sonarr instances but the split is not 4k and non-4k but rather English and German. I have defined the English Radarr/Sonarr instance as the default 4k one and the German Radarr/Sonarr instance as the default non-4k one. This works in that it lets users send requests to the right Radarr/Sonarr instance but the wording in Overseerr is incorrect for my use case (eg. Request 4k movie when really you're requesting a 1080p English movie)

#### Desired Behavior
If I were able to rename the Servers then I would be able to change it from request 4k to request english, making it less confusing for my users.

#### Additional Context
This is just a small usability issue since the core functionality for my use case still works but I believe the proposed change would make Overseerr a better fit for a wider audience (people who have libraries separate by language rather than only resolution).

**Comment by sct** [comment] 2021-08-16 09:49
This is a duplicate of #1881. We will handle this with our request routing feature in the future.

**Closed by sct** 2021-08-16 09:49 UTC
Labels: type:enhancement, awaiting-triage
