### ISSUE TITLE
Discover page recommendations: Toggle to hide available titles

### ISSUE THREAD

**Issue by dtrolley** [sct/overseerr#621] opened 2021-01-11 00:39 UTC
**Is your feature request related to a problem? Please describe.**
The discover suggestions are fantastic, but can often require navigating into the full screen list when the first row of titles already exist in the library.  "Available" titles occupy valuable space that would be better used to show new suggested media.

**Describe the solution you'd like**
A toggle located in settings, to hide "available" media in the upcoming/trending/popular lists.

**Describe alternatives you've considered**
Available media could always be hidden from upcoming/trending/popular by default, without the option to show.  This would not be unreasonable, as suggested titles are typically quite new, and therefore likely to appear in the recently added list anyway.

**Comment by sct** [comment] 2021-01-11 00:40
Duplicate of https://github.com/sct/overseerr/issues/346

**Closed by sct** 2021-01-11 00:40 UTC
Labels: type:duplicate, type:enhancement
