### ISSUE TITLE
Feature Request: Emby/Jellyfin

### ISSUE THREAD

**Issue by cmullins83** [sct/overseerr#865] opened 2021-02-06 14:57 UTC
Support for Emby media server would be fantastic instead of just Plex. (Given the recent events involving Plex, some users have switched over to Emby)

https://www.extremetech.com/internet/319808-plex-media-servers-being-used-to-amplify-ddos-attacks

API Documentation can be found here: https://github.com/MediaBrowser/Emby.ApiClient

**Comment by sct** [comment] 2021-02-06 15:09
Please search next time before opening an issue. And please use the issue template provided!

This is a duplicate of https://github.com/sct/overseerr/issues/295

**Closed by sct** 2021-02-06 15:09 UTC
