### ISSUE TITLE
Telegram notifications somtimes failing

### ISSUE THREAD

**Issue by Dimtar** [sct/overseerr#3434] opened 2023-05-01 11:43 UTC
### Description

For about a month now some notifications are failing to send to Telegram, the logs confirm they were attempted but failed. 
The error code is:
`2023-05-01T11:00:01.473Z [error][Notifications]: Error sending Telegram notification{"errorMessage":"Request failed with status code 400","response":{"description":"Bad Request: wrong file identifier/HTTP URL specified","error_code":400,"ok":false},"subject":"Movie film","type":"MEDIA_AVAILABLE"}`

### Version

1.32.5

### Steps to Reproduce

It doesn't always happen so difficult to reproduce.

### Logs

```shell
2023-05-01T11:00:01.473Z [error][Notifications]: Error sending Telegram notification{"errorMessage":"Request failed with status code 400","response":{"description":"Bad Request: wrong file identifier/HTTP URL specified","error_code":400,"ok":false},"subject":"Movie film","type":"MEDIA_AVAILABLE"}
```

### Platform

desktop

### Device

Any

### Operating System

Docker container - LinuxServer.io

### Browser

Any

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by didyouexpectthat** [comment] 2023-05-02 04:14
I started getting errors wrt Telegram on 4/23 after months of constant use.  I wonder if related to Telegram's recent API upgrades.

```
overseerr    | 2023-04-23T19:20:02.716Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AVAILABLE","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}}
overseerr    | 2023-04-24T11:08:09.593Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AVAILABLE","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}}
overseerr    | 2023-04-25T10:55:01.238Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AVAILABLE","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}}
overseerr    | 2023-04-25T18:37:26.487Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AUTO_APPROVED","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}}
overseerr    | 2023-04-25T19:00:01.059Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AVAILABLE","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}}
overseerr    | 2023-04-29T20:46:21.226Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AUTO_APPROVED","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}}
overseerr    | 2023-04-29T23:36:21.797Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AUTO_APPROVED","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}}
overseerr    | 2023-04-29T23:40:00.991Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AVAILABLE","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}}
overseerr    | 2023-04-30T04:10:03.020Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AUTO_APPROVED","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}}
overseerr    | 2023-04-30T04:20:01.484Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AVAILABLE","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}}
overseerr    | 2023-04-30T23:37:01.962Z [error][Notifications]: Error sending Telegram notification {"type":"MEDIA_AUTO_APPROVED","subject":"x","errorMessage":"Request failed with status code 400","response":{"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}}
```

**Comment by davidfdezalcoba** [comment] 2023-05-17 16:01
I have been seeing this error recently, and have concluded that it is happening because of symbols in the movie name... So far I have had problems with colons (:) and apostrophes ('), but I am pretty sure that is the reason these notifications are failing.

**Comment by broizter** [comment] 2023-07-27 14:27
Still an issue.

**Comment by bgktmxg** [comment] 2023-08-01 04:02
Just commenting to say also an issue for me still. 

**2023-08-01T03:45:05.377Z [error][Notifications]: Error sending Telegram notification{"errorMessage":"Request failed with status code 400","response":{"description":"Bad Request: wrong file identifier/HTTP URL specified","error_code":400,"ok":false},"subject":"800 Words (2015)","type":"MEDIA_AVAILABLE"}**

![screenshot 464](https://github.com/sct/overseerr/assets/51685078/85456e11-d1d1-498e-bc9e-551a501af8fc)

Another notification just 20 minutes earlier worked fine

![screenshot 465](https://github.com/sct/overseerr/assets/51685078/c84fac8e-3e67-4d04-bb69-5a3571823393)

**Comment by mada199122** [comment] 2023-09-06 15:05
even for me

**Comment by NickiS1305** [comment] 2023-09-11 09:48
Same for me, with ( : ) in Movie Name.

**Comment by TheTrueShell** [comment] 2023-10-21 21:48
Still issue, happened with movie with `...` in the name

**Comment by danshilm** [comment] 2024-03-27 17:41
Closing as a duplicate of #3064.
Subscribe to that issue for updates.

**Closed by danshilm** 2024-03-27 17:41 UTC
Labels: type:bug, awaiting-triage
