### ISSUE TITLE
Duplicate Requests In Requests List

### ISSUE THREAD

**Issue by sean-sullivan1** [sct/overseerr#1108] opened 2021-03-07 02:46 UTC
#### Description

The requests list shows duplicate entries for the same movie.

#### Version

develop-778dda67d54df87347dd79577ef1bdc88d3c1d3f

#### Steps to Reproduce

1. A user requests a movie
2. The request shows up twice in requests list

#### Expected Behavior

The request should only show up once in the requests list.

#### Screenshots

![duplicate requests](https://user-images.githubusercontent.com/46687337/110227173-947eea00-7ec3-11eb-865f-40e3d6724a20.PNG)

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** smartphone
- **Device:** iPhone
- **OS:** iOS
- **Browser:** Safari

#### Additional Context

Unfortunately, I have not been able to recreate this issue myself. I think Overseerr may be showing the duplicate items when the item is already monitored in radarr. Near the bottom of the log the string "Radarr. Skipping add and returning success" can been seen. Also the user shown in the screenshot is the same for all of these requests.

Below are the logs for the pertinent time:
`2021-03-06T23:50:20.572Z [[32minfo[39m][Plex Sync]: Beginning to process recently added for library: TV Shows
2021-03-06T23:50:29.064Z [[32minfo[39m][Plex Sync]: Recently Added Scan Complete
2021-03-06T23:51:24.558Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:51:24.571Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:51:25.275Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:51:42.223Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:51:42.225Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:51:42.445Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:51:52.459Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:51:52.462Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:51:52.714Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:52:04.032Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:52:04.035Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:52:04.248Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:52:24.489Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:52:24.491Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:52:24.724Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:52:49.171Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:52:49.173Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:52:49.494Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:53:08.543Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:53:08.547Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:53:09.824Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:53:17.710Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:53:17.714Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:53:18.026Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:53:55.281Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:53:55.284Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:53:55.503Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-06T23:55:00.011Z [[32minfo[39m][Jobs]: Starting scheduled job: Plex Recently Added Sync
2021-03-06T23:55:00.012Z [[32minfo[39m][Plex Sync]: Plex Sync Starting {"sessionId":"a1d0ad1d-42fd-4072-968c-2ca2a432039c"}
2021-03-06T23:55:00.024Z [[32minfo[39m][Plex Sync]: Beginning to process recently added for library: Movies
2021-03-06T23:55:16.520Z [[31merror[39m][Plex Sync]: Failed to process Plex item. ratingKey: 52415 {"errorMessage":"Unable to find TMDb ID","plexitem":{"ratingKey":"52415","key":"/library/metadata/52415","guid":"local://52415","studio":"Walt Disney Pictures","type":"movie","title":"Soul","contentRating":"PG","summary":"Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.","rating":9.8,"audienceRating":9.6,"year":2020,"tagline":"Is all this living really worth dying for?","thumb":"/library/metadata/52415/thumb/1609017933","art":"/library/metadata/52415/art/1609017933","duration":6031567,"originallyAvailableAt":"2020-12-25","addedAt":1609017889,"updatedAt":1609017933,"audienceRatingImage":"rottentomatoes://image.rating.upright","ratingImage":"rottentomatoes://image.rating.ripe","Media":[{"id":81948,"duration":6031567,"bitrate":7469,"width":1920,"height":1080,"aspectRatio":1.78,"audioChannels":6,"audioCodec":"eac3","videoCodec":"h264","videoResolution":"1080","container":"mkv","videoFrameRate":"24p","videoProfile":"high","Part":[{"id":85715,"key":"/library/parts/85715/1609017366/file.mkv","duration":6031567,"file":"/media/Movies/Soul (2020)/Soul (2020).mkv","size":5633416910,"container":"mkv","videoProfile":"high"}]}],"Genre":[{"tag":"Animation"},{"tag":"Family"}],"Director":[{"tag":"Pete Docter"}],"Writer":[{"tag":"Pete Docter"},{"tag":"Kemp Powers"}],"Country":[{"tag":"United States of America"}],"Role":[{"tag":"Jamie Foxx"},{"tag":"Tina Fey"},{"tag":"Ahmir-Khalib Thompson"}]}}
2021-03-06T23:55:20.610Z [[32minfo[39m][Plex Sync]: Beginning to process recently added for library: TV Shows
2021-03-06T23:55:29.516Z [[32minfo[39m][Plex Sync]: Recently Added Scan Complete
2021-03-06T23:56:21.580Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:56:21.589Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:56:21.940Z [[32minfo[39m][Radarr]: Movie is already monitored in Radarr. Skipping add and returning success
2021-03-06T23:56:56.165Z [[32minfo[39m][Notifications]: Sending notification for MEDIA_APPROVED
2021-03-06T23:56:56.167Z [[32minfo[39m][Media Request]: Sent request to Radarr
2021-03-06T23:56:56.588Z [[32minfo[39m][Radarr]: Radarr accepted request
2021-03-07T00:00:00.066Z [[32minfo[39m][Jobs]: Starting scheduled job: Plex Recently Added Sync
2021-03-07T00:00:00.066Z [[32minfo[39m][Plex Sync]: Plex Sync Starting {"sessionId":"ba8be652-f672-4a47-bd91-ef7300d2651c"}
2021-03-07T00:00:00.074Z [[32minfo[39m][Plex Sync]: Beginning to process recently added for library: Movies`

**Comment by sct** [comment] 2021-04-18 10:57
Closing in favor of #1445 just because it has steps to reproduce.

**Closed by sct** 2021-04-18 10:57 UTC
Labels: awaiting-triage, type:bug
