### ISSUE TITLE
No availability icon when searching actors/people

### ISSUE THREAD

**Issue by Bellgore** [sct/overseerr#3187] opened 2022-12-29 09:26 UTC
### Description

When searching for content by actor either threw search or clicking on portrait the list of movies/tv show that come up do not have the green tick in the top right to indicate the availability of content  

### Desired Behavior

The availability tick to show in the top right of the content that is already available when searching by actor.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-12-29 09:36
Duplicate of #3088

**Closed by TheCatLady** 2022-12-29 09:36 UTC
Labels: type:enhancement, awaiting-triage
