### ISSUE TITLE
apple-mobile-web-app-title overwritten

### ISSUE THREAD

**Issue by Treverr** [sct/overseerr#1895] opened 2021-07-14 02:56 UTC
#### Description

apple-mobile-web-app-title is getting overwritten by something. The webpage shows my applicationName but then when I go to add it to my iOS home screen, as many of my users do, it does not work and it shows the default 'Overseerr'. The default is the webpage title, but thats not being populated either.

#### Version

1.25.0

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Change the Application Name
2. Go to iOS -> Safari -> Web App -> Add to Home Screen
3. Observe that the name is Overseerr even though it should not be

#### Expected Behavior

Populates custom Application Name

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Smartphone
- **Device:** iPhone (multiple)
- **OS:** Multiple
- **Browser:** Safari

**Comment by TheCatLady** [comment] 2021-07-14 13:07
Duplicate of #1586

**Closed by TheCatLady** 2021-07-14 13:07 UTC
Labels: awaiting-triage, type:bug
