### ISSUE TITLE
Ability to select quality level (720, 1080, 4K etc) at request & approval time

### ISSUE THREAD

**Issue by scrytch** [sct/overseerr#610] opened 2021-01-09 06:17 UTC
**Is your feature request related to a problem? Please describe.**

When users request movie or show there is no option to choose the quality of the download

**Describe the solution you'd like**

I believe it would be beneficial to have support for:

1. Allow users to request quality level at time of request
2. Allow approver to accept/deny or change quality level at approval time

**Describe alternatives you've considered**
Manually selecting the default server each time before approving a request - which is overly complex and inefficient. 

**Additional context**

ie When someone requests movie, allow them to request (for example) 1080p. Approver receives request, thinks the movie is garbage and doesn't want to waste storage space but still wants to give the requester with poor taste access to the movie and selects 720p instead. Radarr searches and downloads 720p automatically without changing default server before approval.

**Comment by TRaSH-** [comment] 2021-01-09 09:03
this could be combined together with the option that the admin has the option to change more settings.
- used profile
- path

**Comment by sct** [comment] 2021-01-13 12:48
Duplicate of #351 and #514

**Closed by sct** 2021-01-13 12:48 UTC
Labels: awaiting-triage, type:enhancement

**Comment by scrytch** [comment] 2021-01-13 13:19
Hi @sct - appreciate you merging this with #351 but by the way that request reads based on mikeyvt’s description - the desired outcomes seem different? Selecting quality to download has nothing to do with root paths? Unless I am missing something?

**Comment by sct** [comment] 2021-01-13 13:29
It's bundled together. Selecting root folders/quality profiles/servers will all be in the same update.

Example:
![image](https://user-images.githubusercontent.com/234213/104458414-b4461000-55ee-11eb-979f-ce92f1eab241.png)

**Comment by scrytch** [comment] 2021-01-13 19:49
Legend. Thankyou!
