### ISSUE TITLE
Sort network results by air release date

### ISSUE THREAD

**Issue by yueyingjuesha** [sct/overseerr#2361] opened 2021-12-23 06:24 UTC
### Description

I want to track the latest tv shows and movies on a certain TV network, the returned results seem to be sorted by popularity. 

For example Game of Throne always returned as the first show on the HBO network but it has ended a few years ago, I believe many people just want to check out what's the latest shows on a certain network and don't care about whether a show is popular or not.

### Desired Behavior

have a toggle on the network page that can sort the returned results by different types (new season air date, first season air date, popularity, etc.)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-12-23 11:44
Duplicate of #459

**Closed by TheCatLady** 2021-12-23 11:45 UTC
Labels: type:enhancement, awaiting-triage
