### ISSUE TITLE
I really need to use proxy!!!

### ISSUE THREAD

**Issue by zero617** [sct/overseerr#2319] opened 2021-12-01 11:29 UTC
### Description

I am a Chinese person and the timeout when linking to sites such as IMDB causes overseerr to be completely unusable.

### Desired Behavior

I want to be able to set up proxies such as http(s).

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-12-01 11:41
Duplicate of #1907

**Closed** 2021-12-01 11:42 UTC
Labels: type:duplicate
