### ISSUE TITLE
Hide side menu

### ISSUE THREAD

**Issue by dtalens** [sct/overseerr#1455] opened 2021-04-17 22:29 UTC
#### Description

Is your feature request related to a problem? If so, please provide a clear and concise description of the problem. E.g., "I'm always frustrated when [...]."

#### Desired Behavior
Would it be possible to make the side menu be hidden and narrower to have more space for the central part of the web?

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by TheCatLady** [comment] 2021-04-17 22:32
Duplicate of #1203

**Closed by TheCatLady** 2021-04-17 22:32 UTC
Labels: awaiting-triage, type:enhancement
