### ISSUE TITLE
Movies in “Recently Added” marked as “available”, even after being deleted from Plex, Radarr and removed from requests list.

### ISSUE THREAD

**Issue by chibomorto** [sct/overseerr#2285] opened 2021-11-19 16:58 UTC
### Description

Movies in “Recently Added” marked as “available”, even after being deleted from Plex, Radarr and removed from requests list.

If a movie is added to Overseer, it keeps showing on recently added list, even after deletion from Plex, Radarr and Requests list.

The “Play in Plex option” remains available, throwing an error when opening Plex.

Them problem persists even after doing a library re-scan.

### Version

1.27.0

### Steps to Reproduce

1. Go to Overseer Main Page
2. Select a recently added movie;
3. Press “Play on plex”

### Platform

desktop

### Device

PC

### Operating System

Ubuntu Server 20.04, running on docker-compose

### Browser

Chrome 

### Additional Context

I Suggest that recently added movies that are deleted form Plex, Radarr and Overseer Request don’t show-up in the recently added tab.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2021-11-19 17:13
Duplicate of #377

**Closed by danshilm** 2021-11-19 17:13 UTC
Labels: type:bug, awaiting-triage
