### ISSUE TITLE
Filter content with certain keywords

### ISSUE THREAD

**Issue by Bsmith101** [sct/overseerr#2015] opened 2021-08-23 18:33 UTC
#### Description
It'd be great if we could filter out specific content with keywords. TMDb API supports this with the "without_keywords" query string. 

#### Desired Behavior

Be able to enter keywords in settings. Any content that matches the keyword, is filtered out of the discover list.

**Comment by TheCatLady** [comment] 2021-08-23 18:47
Duplicate of #812

**Closed by TheCatLady** 2021-08-23 18:47 UTC
Labels: type:enhancement, awaiting-triage
