### ISSUE TITLE
Add per Show limit options

### ISSUE THREAD

**Issue by mokahless** [sct/overseerr#3364] opened 2023-02-28 17:43 UTC
### Description

I don't like using the per-season (british/overseerr language "per-series") limit because I do not like incomplete shows in my library. Due to stupid end-users, this happens. I've locked in the setting to prevent users from requesting only partial shows and very much appreciate that setting being there.

In my specific case, I want to limit show requests to prevent spam/ excessive per day requests.  It's not the downloading that's an issue; it's the cases where I need to manually intervene, either to fix the source for older shows or stop bad downloads and go to the right place to manually grab more obscure content.  Therefore, the current "per-season" (Brit/over lang. "per-series") limit does not work well as the issues come about from requesting lots of shows at once, not from lots of seasons (Brit/over lang. "series") at once.

### Desired Behavior

A "Global Show Request Limit" similar to the existing "Global Series Request Limit" and "Global Movie Request Limit."

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-02-28 17:53
Duplicate of #1395

**Closed by TheCatLady** 2023-02-28 17:53 UTC
Labels: type:enhancement, awaiting-triage
