### ISSUE TITLE
Incorrect "Aired" tag for episodes

### ISSUE THREAD

**Issue by shark2k** [sct/overseerr#3600] opened 2023-08-27 23:40 UTC
### Description

The "Aired" tag when you expand the section to show the episodes in a season for a TV series is incorrect.
An example (screenshot below) is as of creating this issue (August 27, 2023 at 1928 EDT) is for the final episode (10) of season 4 for Miracle Workers (2019).  You can see in the screenshot below that it says it airs in about 30 minutes, but checking both TheTVDB and TheMovieDB, the episode doesn't actually air un August 28th, which is a whole day later.

I checked and my time zone is correctly set to America/New_York (I'm in NJ) in the settings, so it's not related to that as I looked at the logs screen within Overseer and the time stamps there match the current time on my computer and the time on the server.

### Version

1.33.2

### Steps to Reproduce

1. Go to a TV show that either had a recently aired episode (within 24 hours to make it more noticeable) or has an upcoming episode (within a day or 2 just to make it more easily noticeable as well).
2. Expand the latest season that is currently airing
3. Look at the date the episode airs and the tag that says how many days/minutes until/since the episode aired and you will see the incorrect dae.

### Screenshots

Screenshot of issue:

![image](https://github.com/sct/overseerr/assets/37518107/9ff4a8af-dd50-452f-a0db-1727888ad128)

Screenshot of logs page:

![image](https://github.com/sct/overseerr/assets/37518107/bac6dbff-9f84-4566-884e-19c548bac17e)

### Platform

desktop

### Device

Laptop

### Operating System

Windows 10

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by OwsleyJr** [comment] 2023-08-28 13:54
Duplicate of #3300.

**Closed by OwsleyJr** 2023-08-28 13:54 UTC
Labels: type:bug, awaiting-triage
