### ISSUE TITLE
Ability for multiple requests for the same item from different users

### ISSUE THREAD

**Issue by scallister** [sct/overseerr#2502] opened 2022-02-02 16:04 UTC
### Description

Sometimes two users will try to request the same movie, but if the movie is already requested the second user cannot also make the request.

This would be beneficial because if two users could request the same item, they could both receive e-mails when the item becomes available.

### Desired Behavior

Described above. If an item has an existing request, allowing subsequent requests from different users would be helpful from a notification perspective.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-02-02 16:05
Duplicate of #789

**Closed by TheCatLady** 2022-02-02 16:05 UTC
Labels: type:enhancement, awaiting-triage
