### ISSUE TITLE
First title after inline 'recommended' list is showing twice in 'view all' page

### ISSUE THREAD

**Issue by Zebebles** [sct/overseerr#3277] opened 2023-01-26 11:50 UTC
### Description

G'day! First off, you've done an incredible job of making a clean UI that works great on both desktop and mobile! As a react dev myself, I'm very impressed.

This issue is a minor one, pretty low impact.  The issue title is really all there is to it. I've attached a few screenshots to illustrate.

### Version

1.32.1 (earlier version too, iirc)

### Steps to Reproduce

1. Click on any movie / series
2. Scroll down to recommended
3. Scroll to the end of the list
     - Observe duplicate title cover in the 'see more' buttons background
4. Click 'See more'
5. Scroll until you see one title that appears twice in the list

### Screenshots

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/11425451/214826345-cb013015-4434-46ba-9dea-836ead37ecbc.png">
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/11425451/214826616-65da59a1-2912-43a5-970c-ee0e8a036d22.png">

### Platform

desktop

### Device

Apple Macbook pro m1

### Operating System

MacOS Ventura 13.2

### Browser

Arc (Chromium based)

### Additional Context

App is running on ubuntu server 22.x lts in docker-compose container

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-01-26 16:41
Duplicate of #3040 (see #1996)

**Closed** 2023-01-26 16:41 UTC
Labels: type:bug, awaiting-triage
