### ISSUE TITLE
Adding series for all future seasons (UI)

### ISSUE THREAD

**Issue by jonocairns** [sct/overseerr#1383] opened 2021-04-08 09:02 UTC
#### Description

When adding a series, it'd be nice to know that you are adding for **all future seasons** as well as existing ones.

![image](https://user-images.githubusercontent.com/182836/113997819-9cf48700-98ac-11eb-9adf-51d890039341.png)

The screenshot above is clear for what currently exists, but it's difficult to know what will happen if season 2 comes out. 

I think under the hood if you select the top switch it will send ALL to Sonarr and it will pick up the future seasons - so the functionality is fine but the UI for this could potentially be tweaked slightly. 

I think there are 2 distinct cases 

1. you are monitoring set seasons and NO future seasons
2. you are monitoring all AND all future seasons

#### Desired Behavior

I'd suggest just adding some text to show that future seasons will be included to the ALL selection or tweak the UI slightly and move the switch somewhere else with a set label.

#### Additional Context

This is what Sonarr provides - maybe it's possible to leverage this slightly (I know you wouldn't want to vendor lock to sonarr but the general principle will likely be the same for most tv show monitors)

![image](https://user-images.githubusercontent.com/182836/113998940-a6caba00-98ad-11eb-9585-659cce98ae80.png)

**Comment by TheCatLady** [comment] 2021-04-08 17:50
Duplicate of #478

**Closed by TheCatLady** 2021-04-08 17:50 UTC
Labels: awaiting-triage, type:enhancement
