### ISSUE TITLE
Exclude genres in settings. 

### ISSUE THREAD

**Issue by Zazou89** [sct/overseerr#1204] opened 2021-03-17 00:22 UTC
#### Description

Hello,
For my example, I really don’t like horror movie. When I browse upcoming movie / trending studios and networks I can’t hide horror movies. 

#### Desired Behavior

Possibility in settings to exclude some genres of movies / series.

**Comment by TheCatLady** [comment] 2021-03-17 00:25
Duplicate of #812

**Closed by TheCatLady** 2021-03-17 00:25 UTC
Labels: awaiting-triage, type:enhancement

**Comment by Zazou89** [comment] 2021-03-17 00:29
Hello @TheCatLady,
I think that it’s not really the same things as #812 but thank you for your answer.

**Comment by TheCatLady** [comment] 2021-03-17 02:48
> Hello @TheCatLady,
> I think that it’s not really the same things as #812 but thank you for your answer.

From #812:
`An option to only display items in Overseerr matching a filter, in my case I'd be mostly interested in genre filtering.`
