### ISSUE TITLE
A user can request a single movie multiple times with auto-approve

### ISSUE THREAD

**Issue by wastingaeons** [sct/overseerr#705] opened 2021-01-20 17:36 UTC
**Describe the bug**
A user with auto-approve movie can create duplicate requests. Does not appear to affect auto-approve TV nor requests needing admin approval.

**What version of Overseerr are you running?**
develop-2bfab5e99c04709a1ed45bf30748e4fb5ac95f72

**To Reproduce**
1. On discover or search page hover and request a movie with auto-approve permissions.
2. Click on movie poster to go to details.
3. Hit back button in browser.
4. Observe you can hover over movie and request again.
5. Observe duplicates on /requests page

**Expected behavior**
Duplicates should not be allowed.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/2839483/105212487-62c3e680-5b02-11eb-8535-b88814a9a2ba.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Chrome
- Version: 87

**Smartphone (please complete the following information):**

- Device: OnePlus 6T
- OS: Android 11
- Browser: Chrome
- Version: 87

**Comment by wastingaeons** [comment] 2021-01-21 18:05
Issue persists as described on develop-a3fe4e6321c3480ac0463ed26e0d9be25d88352f

**Comment by sct** [comment] 2021-01-29 02:02
Will take a look.

**Comment by TheCatLady** [comment] 2021-02-19 08:21
Hi @wastingaeons, are you still experiencing this issue? I was investigating this just now but could not repro the problem.

**Comment by wastingaeons** [comment] 2021-02-19 17:51
@TheCatLady I can replicate it consistently on Win10 Chrome & Edge on the latest dev (57c00c1ea71c1229d5a59e1b8dadd84a646772b9). Strangely I can no longer repro from my phone's chrome. 


https://user-images.githubusercontent.com/2839483/108541884-de4abc00-7297-11eb-9d0b-eba017386f57.mp4

Here's a video of it in action in an incognito Chrome window.

**Comment by TheCatLady** [comment] 2021-02-19 17:57
@wastingaeons Thanks for following up!  I think that perhaps it's a browser caching issue, since we hide the request button when there is an existing request.  In your video, you can also see it disappear and only reappear when you press "back."

That said, we shouldn't actually add a duplicate request if one already exists.  I will take a look at this later today 🙂

**Comment by TheCatLady** [comment] 2021-02-19 18:13
@wastingaeons Hi again, could you see if you're able to repro the issue in Incognito mode?  Also, do you have Overseerr behind a reverse proxy?  I've been discussing this with the other devs, and we suspect this is a browser caching issue of some sort.

**Comment by wastingaeons** [comment] 2021-02-19 19:37
Yes, the video is from a fresh incognito window. 

Aha! It is behind a reverse proxy and I am unable to repro from accessing Overseerr directly.

**Comment by TheCatLady** [comment] 2021-02-19 19:39
> Aha! It is behind a reverse proxy and I am unable to repro from accessing Overseerr directly.

Ah, bingo! Closing this issue now since it is unrelated to Overseerr itself. Thanks again for the quick follow-up responses!

**Closed by TheCatLady** 2021-02-19 19:39 UTC
Labels: severity:medium, type:bug

**Comment by TheCatLady** [comment] 2021-02-19 19:42
> Yes, the video is from a fresh incognito window.
> 
> Aha! It is behind a reverse proxy and I am unable to repro from accessing Overseerr directly.
> 
> Edit: Reverse proxy is nginx with LS.io's Swag. Probably outside the scope of Overseer, but like you mentioned, OS shouldn't allow duplicates =)

We actually already added a check to prevent duplicates, but I think that your reverse proxy may be causing issues and preventing the initial request from going through immediately.  I am also using SWAG but could not reproduce the problem.  I suggest checking your SWAG and Overseerr proxy configurations, and seeking help from the appropriate support channels for SWAG if you still experience issues.
