### ISSUE TITLE
Movies Show 'Requested' When Unmonitored and Has Not Been Requested Using Overseerr

### ISSUE THREAD

**Issue by coreyp93** [sct/overseerr#1391] opened 2021-04-09 20:14 UTC
#### Description

I have various trakt lists/personal lists add movies to radarr as unmonitored, and dislike that all unmonitored movies appear as requested in overseerr. 
I personally use monitored/unmonitored to show which movies im _interested_ in downloading, as some i manually search for, and would prefer that overseerr not just assume all movies listed in radarr (monitored or unmonitored) i want (right now). 
Sonarr seems to do what im asking on overseerr though, i just looked and unmonitored shows/seasons dont show as requested? So why is it different for radarr? I dont see why unmonitored movies should be shown as requested when unmonitored by definition are movies not being actively searched for on radarr, and clearly have not been requested either. It adds to confusion for users in not knowing whats actually been 'requested' and being searched for and what is not.  And the button to request does not show, so no way for users to make the movie monitored/request.

#### Version

develop-8ee7693a1f00a2f735b2555c7f8180c8a2c6144f

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Go to Overseerr
2. Click on movies with request status
3. Shows status requested when has not been.

#### Expected Behavior

I expect movies which are unmonitored in radarr not to show 'requested' statuses in overseerr, only show requested for monitored movies. Expect users to be able to request any movie which is unmonitored, making it monitored ready to be searched for. 

#### Device

- Docker
- Synology

**Comment by samwiseg0** [comment] 2021-04-09 20:16
Duplicate of https://github.com/sct/overseerr/issues/1286

**Closed** 2021-04-09 20:17 UTC
Labels: type:duplicate

**Comment by coreyp93** [comment] 2021-04-09 20:24
I commented on that issue and it was marked as off-topic... and your now saying this is a duplicate? I assumed if it was off-topic a separate issue should be made. I am specifically raising the issue of the status being marked, to me, incorrectly. I don't believe that was part of the OPs issue. Would appreciate some clarity as i would like my issue to be heard and not missed. Thanks.

**Comment by samwiseg0** [comment] 2021-04-09 20:32
You are asking why is it different. It is because that was the current design. There is nothing more to add? Your request would be satisfied by the feature request you commented on. There is no need to create a new one.
