### ISSUE TITLE
Filters to point languages & categories to arr/folder

### ISSUE THREAD

**Issue by xplorer990** [sct/overseerr#2556] opened 2022-02-17 10:36 UTC
### Description

Filters to point languages & categories to seperate arr's/folder

### Desired Behavior

Filters to point languages & categories to seperate arr's/folder

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2022-02-17 11:58
Duplicate of #1881

**Closed by danshilm** 2022-02-17 11:58 UTC
Labels: type:enhancement, awaiting-triage
