### ISSUE TITLE
When sending a notification fails due to a bad request (like it can't find a title), it should still send a notification

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#3100] opened 2022-10-30 21:39 UTC
### Description

Seems notifications to telegram sometimes get a 400 because overseer can't find a title.  It should still send the notification, just a less pretty one.  

### Desired Behavior

Send a notification anyway with just text, if it fails to send a fancy one.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by freakshock88** [comment] 2022-12-16 11:33
Agree with this one, I've been missing many notifications due to this error.
The error reported in the logs is this: 

`2022-12-16T11:10:00.552Z [error][Notifications]: Error sending Telegram notification{"errorMessage":"Request failed with status code 400","response":{"description":"Bad Request: wrong file identifier/HTTP URL specified","error_code":400,"ok":false},"subject":"The Fabelmans (2022)","type":"MEDIA_AVAILABLE"}`

**Comment by danshilm** [comment] 2023-02-23 09:20
Closing as a duplicate of #3064

**Closed by danshilm** 2023-02-23 09:20 UTC
Labels: type:enhancement
