### ISSUE TITLE
Auto-Delete Movies/Shows from Radarr/Sonarr

### ISSUE THREAD

**Issue by poloniumTacos** [sct/overseerr#3362] opened 2023-02-27 17:24 UTC
### Description

While I would like this functionality in radarr and sonarr, Overseerr seems like the perfect spot to remove content based off a time or specific condition. I would like to have a feature added like that where I can set default condition applied to all users or by content type once a movie or show is added from when it will be removed from radarr or sonarr (which removes it from plex respectively) if it was requested. I prefer to have this feature for people who request content. 

### Desired Behavior

Auto Delete: Time based, or view based over 30-day period.
Watching content can extend the time before it is auto deleted.
Separate auto delete criteria by content type (Movie auto delete is different from show auto delete)
Notification functionality where you can let users know each week or month what content is being removed and what days etc.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-02-27 19:36
Duplicate of #1924

**Closed by TheCatLady** 2023-02-27 19:36 UTC
Labels: type:enhancement, awaiting-triage
