### ISSUE TITLE
After a request has been deleted once, it can never be requested again by anyone

### ISSUE THREAD

**Issue by dedworks** [sct/overseerr#2305] opened 2021-11-26 04:53 UTC
### Description

After a series request has been deleted once, sometimes (3/7 of my tests) it can never be requested again by anyone. When you try, the button to request it again remains disabled reading "Already requested." 

According to the request history page the series was never requested, according to the request form it is already requested. 

Deletion from the requests queue doesn't seem to consistently delete its entries from the *arrs. When it doesn't, I delete series in the *arrs manually through their own interfaces, but still I can't re-request them.  

So far I can always re-add movies, but I can't always re-add series. 

### Version

d401e33249cbbca6e707479e5f0207e298ef3248

### Steps to Reproduce

Delete a series request.

Decide it was a mistake to delete the request. 

Try to add the same show again, "Already requested"

What next?

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by dedworks** [comment] 2021-11-26 04:59
> It's as if there is a hidden blacklist of series that can't be re-added, and I can't find a way to correct it.

Never mind, I figured out this "hidden list" is just my series data from sonarr.

I expected deleting the request to delete it from sonarr as well, but apparently it doesn't.

**Comment by dedworks** [comment] 2021-11-26 05:12
There's still a problem here, I removed the show from sonarr through its own interface and flushed the caches in /settings/jobs on overseerr, and it still says "Already requested" when I try to request it again.

**Comment by dedworks** [comment] 2021-11-26 05:21
So far it works (lets me add it back) when I delete a movie, but not when I delete a series.

**Comment by dedworks** [comment] 2021-11-26 05:28
Six tries later, I'm getting intermittent results as to whether I can re-add a series after deleting its request. Two of them can't be added back, but four of them can.

**Comment by dedworks** [comment] 2021-11-26 05:48
4 more tests with movies, 4 good results (re-added successfully), problem seems specific to series for me so far, and is affecting a minority of them. 

One thing it isn't doing, consistently deleting the entries from the *arrs when I delete the request...  
After going to overseerr's /requests page and deleting all the random requests I tested with in the past hour, many (but not all!) of the movies and series were still present in the *arrs and needed to be deleted manually through their interfaces.

**Comment by TheCatLady** [comment] 2021-11-26 06:27
Deleting requests does NOT remove them from the *arrs.  Once an item is picked up as being monitored in the *arrs, it will no longer be requestable.  You can reset this by clearing the media data for the item in Overseerr.

**Comment by TheCatLady** [comment] 2021-11-26 06:27
Duplicate of #1196

**Closed by TheCatLady** 2021-11-26 06:27 UTC
Labels: type:bug, awaiting-triage

**Comment by dedworks** [comment] 2021-11-27 04:49
> You can reset this by clearing the media data for the item in Overseerr

This is the piece I was missing, thank you!
