### ISSUE TITLE
Recently added media not deleted if deleted on Plex.

### ISSUE THREAD

**Issue by Zazou89** [sct/overseerr#1364] opened 2021-04-05 08:49 UTC
#### Description

Hello,
I added a lot of media and then deleted them. They still appears on recently added section with an invalid link.

I run all jobs.

#### Version
develop-35c13a87467b4deabab3cb2cd1cab1b24ab51875

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Add media
2. Delete media on Plex

#### Expected Behavior

Deleted medias on recently added

#### Screenshots

/

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** desktop

#### Additional Context

/

**Comment by sct** [comment] 2021-04-05 08:50
Duplicate of https://github.com/sct/overseerr/issues/377

**Closed by sct** 2021-04-05 08:50 UTC
Labels: awaiting-triage, type:bug
