### ISSUE TITLE
New Discord User IDs aren't valid in User ID field

### ISSUE THREAD

**Issue by JoshNotWright** [sct/overseerr#2989] opened 2022-08-26 17:06 UTC
### Description

It seems that the User ID field in the settings is checking for 18 characters, but new discord accounts are getting ids with 19 characters. When I put this user's ID in the field I get:

You must provide a valid user ID

### Version

1.29.1

### Steps to Reproduce

1. Make a new discord account to test (must be a very recent account, I made a test account for other reasons a month or so ago, and it still has an 18 character ID)
2. Copy user ID
3. Go to a user's settings in Overseerr and paste ID into User ID field
4. You will be unable to save, and shown the following error
You must provide a valid user ID

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Brave

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-08-26 17:07
Duplicate of #2860

**Closed by TheCatLady** 2022-08-26 17:07 UTC
Labels: type:bug, awaiting-triage

**Comment by nishanm** [comment] 2022-08-26 18:27
i just discovered this item today. Hopefully its rolled out soon so i can assign the new ids
