### ISSUE TITLE
Deleted items are still shown as "available" in Overseerr

### ISSUE THREAD

**Issue by RaunoT** [sct/overseerr#2872] opened 2022-07-26 21:26 UTC
### Description

I'm not sure if this is an issue that I am facing, or something that has not been implemented, but whenever I remove an item from Plex (irregardless of how), the item is still shown as "available" on Overseerr indefinitely. Manually re-running scan jobs has no effect either. Overseerr just doesn't seem to be able to pick up that the item is no longer available and that it should be allowed to be requested again if need be.

### Version

1.29.1

### Steps to Reproduce

1. Request item via Overseerr
2. Wait for item to become available
3. Delete the item from Sonarr/Radarr
4. (Item no longer exists nor is monitored in Sonarr/Radarr)
5. Item still shows as "available" in Overseerr for an indefinite ammount of time
6. Clicking item "Play on Plex" link leads to Plex error page (as expected)

### Platform

desktop

### Device

PC

### Operating System

Docker (Windows 11)

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-07-26 22:00
Duplicate of #377

**Closed by TheCatLady** 2022-07-26 22:00 UTC
Labels: type:bug, awaiting-triage
