### ISSUE TITLE
Customise notification message components

### ISSUE THREAD

**Issue by M3th0s** [sct/overseerr#769] opened 2021-01-28 20:20 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem, more of an improvement to the current notification system

**Describe the solution you'd like**
The ability to edit the various components that make up the notification message. Like adding/removing the username/alias, etc

**Describe alternatives you've considered**
As of now there are no other alternatives as the notification system can't be customised, only enabled/disabled

**Additional context**
N/A

**Comment by TheCatLady** [comment] 2021-01-28 20:23
This is a dupe of #405.

And as an alternative in the meantime, you can use the webhook notification agent to send custom notifications.  (This is what I'm doing!)

**Closed** 2021-01-28 20:30 UTC
Labels: type:duplicate
