### ISSUE TITLE
add function for movies/series that have not yet been released to the notification list.

### ISSUE THREAD

**Issue by horst789github** [sct/overseerr#2065] opened 2021-09-07 16:02 UTC
#### Description

i have found a movie that is yet to be released, i would like a function that tells me the movie is now available on plex.

#### Desired Behavior

add function for movies/series that have not yet been released to the notification list.

#### Additional Context

old movie, already available, i can request:
![grafik](https://user-images.githubusercontent.com/35397597/132375644-ff0339ef-0f2b-49de-950d-bc04dea3ef47.png)

new movie / not requested by me, but i want to notify me if it available:
![grafik](https://user-images.githubusercontent.com/35397597/132375735-5716337f-b3c3-4ad4-9b31-3dceb7b630ec.png)

**Comment by danshilm** [comment] 2021-09-07 16:08
Duplicate of #789.
Subscribe to that issue for updates

**Closed** 2021-09-07 16:08 UTC
Labels: type:duplicate
