### ISSUE TITLE
Option to override confirmation of requests

### ISSUE THREAD

**Issue by prattable** [sct/overseerr#590] opened 2021-01-06 02:52 UTC
**Is your feature request related to a problem? Please describe.**
I've fallen in the love with the design of this app since it was first brought to my attention via Reddit. So much so that I have personally requested about 300 shows as an admin. Doing so took me roughly 4 hours in total. I had a session where I requested about 150 movies, non-stop, in the span of 3 hours. My issue is that the confirmation doubled my time to request each item where I waited for the confirmation to popup as much as wait for the confirmation to go through and as an Admin I'd like to not have to confirm my choices.

**Describe the solution you'd like**
A new option in the User Permissions section, under the Auto Approve area that disables the confirmation popup.

**Describe alternatives you've considered**
I realize this might not be an issue after a period of time where users have a good chunk of things they want but this option may be very useful in new installations of entire Plex/Sonarr/Radarr/Overseerr packages where the owner doesn't have any media yet or a small collection media that they want to grow quickly, which the design of this app lends itself to very well otherwise.

**Comment by sct** [comment] 2021-01-06 02:55
Duplicate of https://github.com/sct/overseerr/issues/511

**Closed by sct** 2021-01-06 02:55 UTC
Labels: awaiting-triage, type:enhancement
