### ISSUE TITLE
Re-Search Partially Available. 

### ISSUE THREAD

**Issue by Oke11** [sct/overseerr#2555] opened 2022-02-17 00:26 UTC
### Description

I may be missing something, but it seems if you have a partially available season, there is no way for the user to request additional episodes from that partial season, only the next seasons.

Is there any way to do this currently? 

### Desired Behavior

Sometimes I like to get only the Pilot Episodes of certain shows through Sonarr, for people to see it they enjoy it without taking up an entire seasons worth of HDD space unnecessarily. Although right now it seems that if they want to see more, they can't request additional episodes from that season.

The ability to make Sonarr monitor and search partially available seasons would be helpful here. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-02-17 00:34
Duplicate of #349

**Closed by TheCatLady** 2022-02-17 00:34 UTC
Labels: type:enhancement, awaiting-triage
