### ISSUE TITLE
Filter requests by requestor

### ISSUE THREAD

**Issue by jrucker2004** [sct/overseerr#1362] opened 2021-04-04 21:53 UTC
#### Description

Users who don't have access to my plex server still request media, which I then deliver by other methods.  I use the request list to keep track of who has requested what, so it can be delivered correctly.  When the list of items on the requests page is very large, it makes it difficult to find items requested by a specific individual.

Another use case:  If a user is abusing the request system, being able to filter the list of items requested would make it easier to remove items requested by that user.

#### Desired Behavior

A method to allow a user to search or filter the list of requested items using the "requested by" field.
It would be useful to be able to filter by both the "requested by" field and the "status" field at the same time.

**Comment by samwiseg0** [comment] 2021-04-04 21:57
Dupe of https://github.com/sct/overseerr/issues/1181

**Closed by samwiseg0** 2021-04-04 21:57 UTC
Labels: type:duplicate

**Comment by TheCatLady** [comment] 2021-04-04 21:59
Actually, not a duplicate.  However, this has already been implemented.  You can view a user's requests by navigating to their profile page and clicking on the slider.  You can then filter based on the request status in the list view.

**Comment by jrucker2004** [comment] 2021-04-04 22:01
Ah ha!  Thanks for pointing me in the right direction, @TheCatLady 
That's not where I expected it to be.

**Comment by TheCatLady** [comment] 2021-04-04 22:02
@jrucker2004 You can also click on a user's request count in the user list to view their request list.

This functionality was added in #936.

**Comment by jrucker2004** [comment] 2021-04-04 22:05
@TheCatLady Awesome, thanks!  The more I look at this, the more sense it makes.
