### ISSUE TITLE
Possibility to choose what to send on telegram group as request available

### ISSUE THREAD

**Issue by Danguard** [sct/overseerr#2296] opened 2021-11-22 01:07 UTC
### Description

It's not related to a problem:
I would like to ask if it's possible to have the possibillity to choose what will be sent as notification in telegram:

- title
- poster
- description
- link to imdb/tmdb/thetvdb/etc
- requested by
- status

### Desired Behavior

The telegram notification as it is now is really nice, but when posted in a telegram group, specially when there's someone asking for 3-4 things at the same time, it uses a lot of space and read what people write can start to be hard
So.. i thought it would be nice to have the possibility to keep it to the minimum needed 

Thank you

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-11-22 01:18
Duplicate of #405

**Closed by TheCatLady** 2021-11-22 01:18 UTC
Labels: type:enhancement, awaiting-triage
