### ISSUE TITLE
Support for multiple notifications for a single Agent

### ISSUE THREAD

**Issue by MarcStocker** [sct/overseerr#2393] opened 2022-01-05 02:51 UTC
### Description

Currently each notification agent only supports one notification configuration. With the implementation of the "issues" feature, it would be beneficial to give users the ability to define multiple notification configurations in order to separate different types of notifications. 
For example, when using Discord, if you want to have notifications for both issues, and new content, you are forced to post all notifications in the same channel due to only being able to define a single Webhook. This can get messy, and sometimes not all users need to see all the information. 

### Desired Behavior

(My examples will be Discord based specifically). 
Each notification agent could have an "Add" button that generates an additional list of the same notification options so they can be sent using a different bot username, to a different channel, or sent to specific people. 

So for the Discord agent, this would give you the ability to define multiple webhooks, each with it's own bot Username, Icon, and set of notifications it can send out. 

### Additional Context

I'd love to be able to separate my "Issues" notifications from my "New content" and "New Request" notifications. Users other than myself do not need to see the spam of new requests and additions. But I'd still like to have them as a form of "logging" system so I can see when things are happening. 

This would also help users keep track of the information they actually want to see. Rather than being forced to wade through the various notification types to find what they're looking for. 

If the admin did not want to separate notifications into different channels, this would still give them the ability to give each notification type it's own bot username and icon to better suite what the notification is for (in addition to the text and comment side bar color). 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-01-05 03:06
Duplicate of #1664

**Closed by TheCatLady** 2022-01-05 03:06 UTC
Labels: type:enhancement, awaiting-triage

**Comment by davidnewhall** [comment] 2022-07-25 01:29
And duplicates #1588 and #972. Seems to be a popular request since it was added from the request in #620.
