### ISSUE TITLE
Display Download Progress when Processing status

### ISSUE THREAD

**Issue by polklabs** [sct/overseerr#1300] opened 2021-03-26 21:12 UTC
#### Description

When a show or movie is downloading it syncs with Radarr/Sonarr and shows the status as "Processing..." (which is awesome)
Users sometimes ask me when a movie will be added when it's already in the processing state, instead of going to lookup the download progress and give them an ETA I could just point them back to their Overseerr request.

#### Desired Behavior

It would be great if, at least for movies, the download percentage was displayed. It might be too tricky for tv shows since they can download in a lot of different chunks.

If there are multiple versions of the same movie downloading it could show the version with the highest percentage.

So the status would change from:
"Processing..." to "Processing... (34%)"

#### Additional Context

In the Radarr/Sonarr Activity Queue there is a column for download progress, haven't looked to see if that is available though their APIs

**Comment by TheCatLady** [comment] 2021-03-26 21:28
Duplicate of #994

This should be covered by what @sct has planned for #994, which would provide the option of exposing the download status to non-admin users.

**Closed by TheCatLady** 2021-03-26 21:28 UTC
Labels: awaiting-triage, type:enhancement

**Comment by Laiteux** [comment] 2022-09-19 21:27
This might be relevant for anyone stumbling upon this issue or looking for this feature: https://github.com/sct/overseerr/issues/3028#issuecomment-1251577092

**Comment by pir8radio** [comment] 2025-04-27 01:48
Yes here is another option for people who find this thread (like I did a few weeks ago)  I ended up making an arr to show actual download progress, time remaining, and reason for stalled downloads.   So users can do some troubleshooting on their own. 

https://github.com/pir8radio/DownloadViewarr
