### ISSUE TITLE
[Request] Automatic deletion if content not watched within X days

### ISSUE THREAD

**Issue by jotafett** [sct/overseerr#3104] opened 2022-11-01 00:30 UTC
### Description

To save storage, an option to delete requests that aren't watched within X days. 

### Desired Behavior

With the feature enabled and set to 30, Tautulli will detect if the status of an Approved Request is watched. If the request isn't watched within 30 days, delete it from Sonarr/Radarr. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-11-01 00:56
Duplicate of #1924

**Closed by TheCatLady** 2022-11-01 00:56 UTC
Labels: type:enhancement, awaiting-triage
