### ISSUE TITLE
Show Missing Episodes from TV-Show at Requist

### ISSUE THREAD

**Issue by swoop124** [sct/overseerr#2147] opened 2021-09-30 19:05 UTC
#### Description

Add a display that shows witch Episodes from a TV-Show is missing

#### Desired Behavior

When requesting a Show or Season it should display witch Episode is already there or missing

**Comment by samwiseg0** [comment] 2021-09-30 19:23
Currently this is not possible since we do not track the individual episodes. I believe this would be available once this feature is implemented. https://github.com/sct/overseerr/issues/342

Duplicate of https://github.com/sct/overseerr/issues/342

**Closed by samwiseg0** 2021-09-30 19:23 UTC
Labels: type:duplicate
