### ISSUE TITLE
Support for multiple plex servers

### ISSUE THREAD

**Issue by MikeFez** [sct/overseerr#2155] opened 2021-10-02 02:21 UTC
#### Description

I manage multiple Plex servers under a single Plex account, as in, I have it installed on multiple machines (one at my house, one at my parents). When set up this way, you can create libraries per location and most apps that connect to Plex allow users to toggle between servers to watch media from libraries on each. Overseerr can in fact see both servers under an account, but it will only allow me to select one at a time.

I have Radarr & Sonarr instances in both locations, (and now Overseer instances) to manage both sets. In Overseer, I configured the "local" Plex/Radarr/Sonarr instances per location and it does work. That being said, since Radarr/Sonarr/Plex can all be accessed remotely, it's a bit of a pain to have to jump between Overseer instances specifically to manage requests. Furthermore, this leads to duplication of files between the Plex servers since Overseer only monitors the libraries of one server at a time, rather than the entirety of media available on the Plex account. So if I have media available on my home server that users in my parent's house also request, the same media is downloaded twice.

#### Desired Behavior

I'd love the ability to connect multiple Plex servers (or even separate accounts for those that may need it) to Overseerr. A simplistic solution would be to allow for multiple servers to be selected, allowing for the libraries from each to be grouped together and monitored in full. I could then add Radarr/Sonarr from both locations to a single Overseer instance and have users route requests to wherever is relevant to them.

A more in-depth solution would be to allow multiple servers, and tie Radarr/Sonarr instances to a specific server. So I'd have Radarr/Sonarr and their 4k variants tied to my Plex server, and then I'd have my parent's instances tied to theirs. Plex servers themselves could be tied to a user so that when they request media, it's automatically routed to their Radarr/Sonarr instance and then populates on their Plex server, while still providing them the ability to see what media is requested or available on mine (so if I request an item on my server, it's marked as requested already even if it's not in their local Radarr/Sonarr instance).

Whew, that's a lot of "Radarr/Sonarrs" up there. Thanks for taking the time to read this.

#### Additional Context

Here's a screenshot of Overseer's Plex server selection dropdown in my situation, with it successfully detecting both Plex instances under my account. It would be nice if I could select multiple options from here:

![plex](https://user-images.githubusercontent.com/2111621/135700507-96ad707e-ee77-480e-839f-be3604330596.png)
.

**Comment by TheCatLady** [comment] 2021-10-02 02:55
Duplicate of #1094

**Closed** 2021-10-02 02:55 UTC
Labels: type:enhancement, awaiting-triage
