### ISSUE TITLE
Can't request tv show episodes when season partially available

### ISSUE THREAD

**Issue by csihama** [sct/overseerr#1092] opened 2021-03-05 00:42 UTC
Hi,

I have a problem with TV show episode request, when the tv show season partially available on plex.

Example: Tv show was not added to sonarr before. Overseerr only synced from plex. Tv show season 1 available 5/10 on plex. When I want to request more episode from a partially available season, I can't choose any, because the season toggle is fixed on request position and request button greyed out, can't do anything.

I tried the same thing on Ombi, they did the season toggle not fixed (switchable), show the full episode list and can request individual episodes or all unavailable episodes.

Thanks for any help :)

**Comment by TheCatLady** [comment] 2021-03-05 00:43
Duplicate of #349.

**Closed by TheCatLady** 2021-03-05 00:43 UTC
Labels: awaiting-triage, type:bug
