### ISSUE TITLE
Music addition to Plex

### ISSUE THREAD

**Issue by nicholasyoannou** [sct/overseerr#2455] opened 2022-01-23 20:35 UTC
### Description

No, just generally I would like so users can request albums and such to add music to my Plex. I'd love that to be a thing, that'd be a great addition.

### Desired Behavior

The same practical functionality as movies, but instead with albums of music. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2022-01-23 20:36
Duplicate of #352

**Closed by danshilm** 2022-01-23 20:36 UTC
Labels: type:enhancement, awaiting-triage
