### ISSUE TITLE
Add ability to hide existing media in Trending/Popular/Upcoming

### ISSUE THREAD

**Issue by citadella** [sct/overseerr#584] opened 2021-01-05 14:41 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like the ability to hide any existing media in Trending/Popular/Upcoming. As I have a ton of media, almost nothing which is in these categories is actually *new* for me, and I'd like to be able to browse through new popular shows/movies that I don't already have

**Describe alternatives you've considered**
Just creating a 'new to you' or 'suggested' list which would be one or all of these Trending/Popular groups, filtered by media not present.

**Additional context**
As you can see, nearly all of these are already present. I see Overseerr as a new media location tool, not a media-browsing tool. If other people see it differently, that's fine, but giving us the option of hiding already-present media would let us both be happy:
![image](https://user-images.githubusercontent.com/31351568/103659221-73a22300-4f6c-11eb-9db7-35e189f2663a.png)

**Comment by sct** [comment] 2021-01-05 15:04
Duplicate of https://github.com/sct/overseerr/issues/346

**Closed by sct** 2021-01-05 15:04 UTC
Labels: awaiting-triage, type:enhancement
