### ISSUE TITLE
Logs page in settings shows 500 - Internal Server Error

### ISSUE THREAD

**Issue by shomilsaini** [sct/overseerr#2456] opened 2022-01-23 22:14 UTC
### Description

Going to Logs page under settings shows 500 - Internal Server Error

### Version

1.28.0

### Steps to Reproduce

1. Go to settings
2. Click on logs tab

### Screenshots

![image](https://user-images.githubusercontent.com/46788173/150699950-c9240ecd-7136-4e8c-b95d-95ef3dfe2003.png)

### Logs

```shell
2022-01-23T22:11:19.542Z [error][Logs]: Something went wrong while fetching the logs {"errorMessage":"Unexpected end of JSON input"}
```

### Platform

desktop

### Device

Windows

### Operating System

Windows 11

### Browser

Chrome

### Additional Context

Installed under Docker in UnRaid

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by shomilsaini** [comment] 2022-01-23 22:15
Re-installed the container, no change.

**Comment by TheCatLady** [comment] 2022-01-23 22:15
Duplicate of #2451

**Closed by TheCatLady** 2022-01-23 22:15 UTC
Labels: type:bug, awaiting-triage

**Comment by shomilsaini** [comment] 2022-01-27 20:35
Still shows the same error, is it fixed? I dont understand.

`2022-01-27T20:32:18.049Z [[31merror[39m][Logs]: Something went wrong while fetching the logs {"errorMessage":"Unexpected end of JSON input"}`

**Comment by TheCatLady** [comment] 2022-01-27 21:25
> Still shows the same error, is it fixed? I dont understand.

The fix is being verified in the `develop` branch and will be included in the next release.
