### ISSUE TITLE
Music or Book support (Lidarr, Readarr)

### ISSUE THREAD

**Issue by RemoteMedia** [sct/overseerr#1922] opened 2021-07-24 04:46 UTC
#### Description

Not listed as a problem. Im not too sure if Readarr / book request has been made before. I think that for all self-hosting managers the things that tend to bog me down are requests for things that download super quickly. I'm getting multiple book and album requests through my discord. Ombi fulfills the music, but I prefer Overseerr for movies and shows as its just really intuitive and has such a great layout.

#### Desired Behavior

To be able to request music and/or books

#### Additional Context

Nil.

**Comment by TheCatLady** [comment] 2021-07-24 05:04
Duplicate of #352 and #605

**Closed by TheCatLady** 2021-07-24 05:04 UTC
Labels: awaiting-triage, type:enhancement
