### ISSUE TITLE
Overseerr Not Marking Missing/Deleted Content as Unavailable Automatically

### ISSUE THREAD

**Issue by rockerguy1978** [sct/overseerr#1950] opened 2021-08-01 00:42 UTC
#### Description

I recently experienced an issue with my HDDs that caused me to lose my entire media collection (over 300 movies). Once storage issues were resolved and restored, I tried to rescan the content manually via the Plex Full Media scan option. However, Overseerr is not marking the content which is permanently gone as unavailable. I want users to be able to re-request the content if needed.

#### Version

1.25.0

#### Steps to Reproduce

Jobs & Cache > Plex Full Library Scan

#### Expected Behavior

After a full scan, if lots of content is missing (in my case over 300 movies), Overseerr should mark the content as unavailable again automatically

#### Screenshots

Not required

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** Server
- **Device:** Custom Whitebox Server
- **OS:** Ubuntu 20.10 LTS
- **Browser:** Not applicable. But using Chrome

**Comment by danshilm** [comment] 2021-08-01 01:14
Duplicate of #377. Follow that issue for updates.
For now, the simplest way to mark a lot of content as unavailable is to delete the database (`.sqlite* files in your config folder`). However, this also means that you will lose the request history for all users.

**Closed by danshilm** 2021-08-01 01:14 UTC
Labels: awaiting-triage, type:bug
