### ISSUE TITLE
Collapsible navigation side bar for landscape orientation on tablets

### ISSUE THREAD

**Issue by hwwilliams** [sct/overseerr#1814] opened 2021-06-18 22:27 UTC
#### Description

When using a tablet in landscape orientation the navigation side bar is larger then I think it needs to be as I feel like that space could be better used to see posters and other content.

#### Desired Behavior

It would be nice if the navigation side panel could be compacted or collapsed similar to the normal mobile site on mobile phones.  

#### Additional Context

I've included a picture showing what it looks like in landscape orientation on a tablet.

![image](https://user-images.githubusercontent.com/20447447/122620949-3a64f780-d062-11eb-8280-296f95a0fd21.png)

**Comment by samwiseg0** [comment] 2021-06-18 23:51
Duplicate of https://github.com/sct/overseerr/issues/1203

**Comment by samwiseg0** [comment] 2021-06-18 23:52
Reopening https://github.com/sct/overseerr/issues/1203 and we can track this there. 

Thanks

**Closed by samwiseg0** 2021-06-18 23:51 UTC
Labels: awaiting-triage, topic:ux, type:enhancement
