### ISSUE TITLE
Ability to add year to the request search

### ISSUE THREAD

**Issue by JeramieG-IDG** [sct/overseerr#630] opened 2021-01-11 20:29 UTC
**Is your feature request related to a problem? Please describe.**
many searches return dozens if not hundreds of results depending on the complexity of the title.

**Describe the solution you'd like**
if the user were able to search for title (year) that could solve the issue.  For example Cherry (2021) would result in the upcoming apple tv movie.

**Describe alternatives you've considered**
it could also be useful to sort search results by release date

**Additional context**
i wish i could remember the name of the title, but i searched for something a few days ago and there were tons of results, it was a single word title.  Anyways, the one i wanted was several pages in, i knew the release year and tried adding that to the search but that returned 0 results of course.

**Comment by sct** [comment] 2021-01-11 22:49
I believe https://github.com/sct/overseerr/issues/459 can include this

**Comment by sct** [comment] 2021-01-13 12:53
Duplicate of #459

**Closed by sct** 2021-01-13 12:53 UTC
Labels: awaiting-triage, type:enhancement

**Comment by runaroundhome** [comment] 2023-02-21 01:43
https://github.com/sct/overseerr/issues/459 has now been implemented, but when I try to search for "Cherry (2021)" or "Cherry 2021" it returns 0 results.
Am I doing it wrong?

**Comment by hwwilliams** [comment] 2025-07-09 06:14
@sct This still doesn't seem to be implemented based on what was done in https://github.com/sct/overseerr/issues/459

It seems like the original intent was to allow searching for a specific title and year combination to cut down on results since a lot of movies and shows reuse titles, the linked issue focuses on providing filtering options for the discover feature which is unrelated to search results.
