### ISSUE TITLE
Improve "Requests" page.

### ISSUE THREAD

**Issue by SimonBrooker** [sct/overseerr#686] opened 2021-01-19 09:43 UTC
**Is your feature request related to a problem? Please describe.**
I'm frustrated that hitting "requests" doesn't show all requests immediately, I need to click another "show all requests" button.

**Describe the solution you'd like**
I think it would be good to immediately show all requests but have another column for pending/approved that can be filtered. Maybe change the current status column to "Media Status" and the new column to "Approval Status".

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sct** [comment] 2021-01-19 09:52
Duplicate of https://github.com/sct/overseerr/issues/616

**Closed by sct** 2021-01-19 09:52 UTC
Labels: awaiting-triage, type:enhancement
