### ISSUE TITLE
You closed it last time but the website has it correct and my timezone is correct?

### ISSUE THREAD

**Issue by mrwestside12** [sct/overseerr#3290] opened 2023-01-27 16:42 UTC
### Description

This issue is not on TMBD this date is only showing up on Overseerr. Ombi has the date correct Sonarr Radarr has dates correct. Every date is a day early on overseerrr. 

### Version

newest 

### Steps to Reproduce

Look at any air date 

### Platform

desktop

### Device

Any

### Operating System

Any

### Browser

Any

### Additional Context

Closed and not resolved last time 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2023-01-27 20:10
Duplicate of #3289 

Please do not create duplicate issues. You can comment on the previously created issue.

**Closed by TheCatLady** 2023-01-27 20:10 UTC
Labels: type:bug, awaiting-triage
