### ISSUE TITLE
Support multiple notification agents for the same provider

### ISSUE THREAD

**Issue by clee** [sct/overseerr#3060] opened 2022-10-02 17:20 UTC
### Description

I'd like to be able to send notifications to multiple Slack servers, or multiple webhooks, etc.

### Desired Behavior

Instead of having a sort of "tab"-style navigation interface like this: 
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2089/193467283-3433bc18-0434-462f-b3c4-bb4ee382866a.png">

Perhaps the notifications agents page could be a list, with a "New notification agent" button to add a new agent of whatever type you want, without being limited to one notification agent per provider/method.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-10-11 01:00
Duplicate of #1664

**Closed by TheCatLady** 2022-10-11 01:00 UTC
Labels: type:enhancement, awaiting-triage
