### ISSUE TITLE
Add permission for users to manage their own requests (once approved) + an ongoing request limit

### ISSUE THREAD

**Issue by keldian** [sct/overseerr#1961] opened 2021-08-04 18:39 UTC
#### Description

Overseerr has all the groundwork laid out for offloading some of the library management to shared users, instead of having the admin do all the work, but currently the available settings don't allow it.

#### Desired Behavior

1. A setting for the user to be able to delete their own request, triggering removal in *arr, Plex and of the data, regardless of the state of the request. 

2. A request limit of X items at any given time (which doesn't reset on a timely basis). Once the limit is reached by a user, in order to make a new request, they will have to delete an existing request from their requests library.

Why? This way the admin won't have to worry about checking if the user has watched the item, or no longer wants to watch the item, when deciding what to remove to free up storage space. On top of that, it prevents the requests section of Overseerr from getting cluttered.

**Comment by TheCatLady** [comment] 2021-09-28 16:45
Duplicate of #1924

**Closed by TheCatLady** 2021-09-28 16:45 UTC
Labels: type:enhancement, awaiting-triage
