### ISSUE TITLE
Abilty to disable Plex Oauth for Users and Owner

### ISSUE THREAD

**Issue by sgtcoder** [sct/overseerr#3077] opened 2022-10-15 22:44 UTC
### Description

Everyone is having issues with Plex. Nobody can stream from it, no one can login with Plex Oauth. Plex used to be wonderful, but now it's horrible and buggy.

I ONLY have Plex setup on a private network just to sync the Library with Overseerr and I use Emby.

The problem is, most users are trying to login with their Plex account and not clicking on Login Locally. Since Plex is always having issues and they click Login with Plex, they are getting Access Denied issue.

### Desired Behavior

1. When setting up a new Overseerr, have an option to login locally.
2. Have an option to DISABLE Plex Oauth from the login screen (it does not work), or just quickly add an option to hide the html for it.
3. Allow previous Plex users have an option to convert to Local account, setting a password does not work.

### Additional Context

The problem is with Plex, and making it a requirement is causing issues. Overseerr is the only greatest requester we have. Ombi doesn't even come close.

I do know you are in the process of unlinking everything.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-10-17 21:06
Duplicate of #2557

**Closed by TheCatLady** 2022-10-17 21:06 UTC
Labels: type:enhancement, awaiting-triage
