### ISSUE TITLE
Enable local account admin

### ISSUE THREAD

**Issue by J4gQBqqR** [sct/overseerr#2397] opened 2022-01-06 14:11 UTC
### Description

I do not have a Plex account and nor do I plan to use Plex in the future.
The first welcome screen offers option for admin to use Plex and **only** Plex to proceed.
I simply cannot go anywhere without Plex account.

### Desired Behavior

Be able to use the software without any Plex account.

### Additional Context

Maybe adding a local admin option would be the first step.

However, since I did not go further into testing the software, I am not aware if there is anywhere else in the software that a Plex account is required. If there is any, it might be worth considering to remove the hardwired dependency of Plex.

The current setting is not friendly to non-Plex users. Please take into account that there are lots of people who use sonarr etc only with Kodi, VLC, Potplayer, Jellyfin, EMBY etc. Plex is not the only player out there.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-01-06 14:13
Duplicate of #917

**Closed by TheCatLady** 2022-01-06 14:13 UTC
Labels: type:enhancement, awaiting-triage

**Comment by J4gQBqqR** [comment] 2022-01-06 14:40
Sorry, I did not find the pointed issue. 
Thank you for the information.
It is sad that Kodi, VLC users are left out from consideration.

**Comment by danshilm** [comment] 2022-01-06 16:33
The changes required to make it possible for Emby/Jellyfin to be supported will also be a step towards using Overseerr without a media server. But Emby/Jellyfin will probably happen first. There was a big pull request for adding support for those (#940) but, you can see from the comments on that pull request that it's a big undertaking and we want to get it done properly.

Honestly, for now, I'd just recommend spinning up an instance of Plex in a container or something, point it to your media libraries, and use that to set up Overseerr. Then just let it do its thing; you don't have to use Plex, just let it sit there for Overseerr to connect to and work.

**Comment by danshilm** [comment] 2022-01-17 14:41
> > 
> 
> @danshilm this would work for sure, but that totally breaks the whole purpose of this : enabling **other users** to request contain. The admins don't care much about Overseer, they just use Sonarr/Radarr/etc directly. The main purpose of overseer or ombi is precisely to open your tools to your media center users, without having them accessing the tools directly. And that's why both app have auto user-creation capabilities, from the media center users. 
> Going your way will force admins to manually manage all users, which is not convenient at all.
> 
> So really looking forward for a Jellyfin integration. Going Plex-only for an open-source project like this, goes beyond my understanding....

I was merely suggesting that as a temporary workaround. Of course there's caveats, limitations, quite a bit of manual work involved, and it's not a solution. It's just for those who find the workaround worth it.
