### ISSUE TITLE
Unable to add foreign (Serbian) TV show 

### ISSUE THREAD

**Issue by citadella** [sct/overseerr#583] opened 2021-01-05 14:33 UTC
**Describe the bug**
Two of my users have tried to add the show Morning Changes Everything(2018) (http://xxxx:5055/tv/84373) (https://www.themoviedb.org/tv/84373) and it recognises the 1 season, allows me to select it, and then nothing happens when I click 'Request 1 Season'

**What version of Overseerr are you running?**
1.15.0

**To Reproduce**

Attempt to add TMDB 84373

**Expected behavior**
Add

**Screenshots**
![image](https://user-images.githubusercontent.com/31351568/103658113-15287500-4f6b-11eb-9204-a2f2d14a1f3f.png)

**Desktop (please complete the following information):**

- OS: Mac Big Sur
- Browser [Brave, Safari]

**Comment by ankarhem** [comment] 2021-01-05 14:39
Duplicate of #562

**Comment by danshilm** [comment] 2021-01-05 14:50
Added the TVDB id to the TMDB listing. I think we might have to wait a full day for it to take effect though (based on the last time something like this happened).

**Comment by citadella** [comment] 2021-01-05 14:56
Thanks for the fast updates!

**Closed** 2021-01-05 15:07 UTC
Labels: awaiting-triage, type:bug
