### ISSUE TITLE
Ability to choose directory for 'Collections'

### ISSUE THREAD

**Issue by dmnchild** [sct/overseerr#2369] opened 2021-12-26 10:32 UTC
### Description

Would be nice to choose where collections go, so if its an animated, anime, kids, horror, and people have corresponding sections they would like them in, they would all save there instead of the default location.

### Desired Behavior

Pull down's for sections, just like we have when adding singles.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2021-12-26 10:44
That's actually already available on the `develop` branch with #1742 and will be in the next release

**Comment by danshilm** [comment] 2021-12-26 10:44
Closing as a duplicate of #1739

**Closed by danshilm** 2021-12-26 10:44 UTC
Labels: type:enhancement, awaiting-triage
