### ISSUE TITLE
Personalized Media Recommendations

### ISSUE THREAD

**Issue by SpecialBus** [sct/overseerr#730] opened 2021-01-23 16:48 UTC
**Describe the solution you'd like**
Add a 'Your Suggestions' section to the main UI.  This section will give media recommendations based on past requests.  When clicking on a poster in this section, add a UI element to the details page that lists what all requests were used to come up with said suggestion.

**Comment by samwiseg0** [comment] 2021-01-23 17:46
Dupe of https://github.com/sct/overseerr/issues/459

**Closed** 2021-01-23 17:47 UTC
Labels: type:duplicate
