### ISSUE TITLE
Feature Request: Sort/Filter Media Results Pages

### ISSUE THREAD

**Issue by natelandau** [sct/overseerr#1637] opened 2021-05-13 19:58 UTC
#### Description

Currently, entering any media results page (ie clicking a network name, a genre, a studio name, etc.) results are displayed but there is no control over the sort of the media.  It would be very useful to have a sort and/or filter functionality to allow you to order the results on the page by:

* Release date (sort)
* TMDB and/or Rotten Tomatoes rating (sort)
* Status (Filter)
* Studio/Network (Filter)
* Language (Filter)

This is fantastic software that I just found today.  It's awesome, keep up the good work

**Comment by TheCatLady** [comment] 2021-05-13 20:22
Duplicate of #459

**Closed by TheCatLady** 2021-05-13 20:22 UTC
Labels: awaiting-triage, type:enhancement
