### ISSUE TITLE
User Display Name

### ISSUE THREAD

**Issue by hirenshah** [sct/overseerr#665] opened 2021-01-17 18:23 UTC
**Is your feature request related to a problem? Please describe.**
I would like to set my own Display Names for user accounts because I have no control over the Plex or Local User ones. 

**Describe the solution you'd like**
An additional Display Name field for all users, and have that value displayed in the UI.

**Describe alternatives you've considered**
Closing my eyes and crying (the existing user names are triggering my OCD)

**Additional context**
Display Name feature like Ombi:
![image](https://user-images.githubusercontent.com/418112/104852160-09389d80-58f1-11eb-9518-3398be9f8423.png)

**Comment by samwiseg0** [comment] 2021-01-17 18:58
Dupe of https://github.com/sct/overseerr/issues/264

**Closed by samwiseg0** 2021-01-17 18:58 UTC
Labels: type:duplicate
