### ISSUE TITLE
Ability to hide/blacklist Shows/Movies

### ISSUE THREAD

**Issue by FSCorrupt** [sct/overseerr#1382] opened 2021-04-08 05:38 UTC
#### Description

Recently, i had a problem, that Sonarr redownloaded a show from a user request, that show was a reality show, so i set a exlusion to not contain the show title (but it still doesn't work), user keeps requesting it.. And sonarr downlods this shows.... 

it would be really cool to have the ability as an Admin, to hide certain shows/movies or even genre for my Users!

**Comment by TheCatLady** [comment] 2021-04-08 05:39
Duplicate of #812

**Closed by TheCatLady** 2021-04-08 05:39 UTC
Labels: awaiting-triage, type:enhancement
