### ISSUE TITLE
Add a Message of The Day (MOTD) Banner

### ISSUE THREAD

**Issue by Minituff** [sct/overseerr#3262] opened 2023-01-21 20:02 UTC
### Description

I would love to be able to configure messages that all users who sign into my server can see. I currently use Overseer as my only entry point for my users to request content, report issues, and view content status for all things on my Plex server. Because it is so easy to use, I even have my *non-techy* family members able to use it with ease. There is only 1 feature that belive is missing, banners.

For example, let's say I want to perform scheduled server maintenance. Instead of getting calls and texts asking my why Plex is down, I could have a banner up on Overseer.

### Desired Behavior

There are two places I was considering for a banner:

1. The existing top banner which now reads `This is BETA software. Features may be broken and/or unstable. Please report any issues on GitHub!`. 
2. Or a modal popup that can be easily dismissed. I think this will be a great way to keep my users aware of any changes to the server.

Bonus points if:

- I can update the MOTD via an API
- The MOTD can display the Plex/Sonarr/Radarr status. This would be great because I will sometimes get texts asking if plex is down, but Overseer is still up.
-  Add markdown support to the MOTD, so I could add links, bolden or italicize items, etc. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2023-02-23 09:11
Closing as a duplicate of #3138

**Closed by danshilm** 2023-02-23 09:11 UTC
Labels: type:enhancement
