### ISSUE TITLE
URL prefix

### ISSUE THREAD

**Issue by VanadiumJade** [sct/overseerr#1905] opened 2021-07-16 04:40 UTC
#### Description

I would be great if overseerr had the option to add a configurable prefix to URL.
This will allow the ability to easily add a load balancer over the top

#### Desired Behavior

UI configuration option to add URL prefix. For example if I configured this option to be foobar
http://host:5055/requests => http://host:5055/foobar/requests
http://host:5055/users => http://host:5055/foobar/users
or
http://host:5055 => http://host:5055/foobar

#### Additional Context

So if you want DR then you can have
http://balancer/overseer
http://balancer/overseer/requests
http://balancer/overseer/users
(without having to do URL rewrites)

And the balancer would distribute to available host/s.

So in my case if a OS update is required or a host outage then... I can take down node 1 and node 2 will will fire up node 1 resources.

transmission/radarr/sonarr all support this concept.

**Comment by samwiseg0** [comment] 2021-07-16 04:51
As this maybe a cool idea I dont see the practicality in it since the database would not be shared with your other instances or what value this would offer most users.

Please see the base url issue for information on how this may not even be possible with express unless you compile it from source for each instance and define your prefix. https://github.com/sct/overseerr/issues/274

I think for something this custom you can make the appropriate modifications to the code and deploy your own instances from source.

**Comment by VanadiumJade** [comment] 2021-07-16 05:25
Yeah its niche.

Yeah I understand you cant fire up instances of overseer at the same time, but you can take one node down and second node will recover services with no effort at all - just automatic. While you do what you need to on the first node.

But if not possible or useful for peoples time... I will investigate a more janky option with nginx haha. :)

**Comment by samwiseg0** [comment] 2021-07-16 05:38
Check out the "janky" work around we have for base url in the docs. That may give you what you need to make it work.

**Comment by sct** [comment] 2021-07-16 06:03
Duplicate of https://github.com/sct/overseerr/issues/274

**Closed by sct** 2021-07-16 06:03 UTC
Labels: awaiting-triage, type:enhancement
