### ISSUE TITLE
Anime not being picked up

### ISSUE THREAD

**Issue by modem7** [sct/overseerr#453] opened 2020-12-22 03:45 UTC
**Describe the bug**
Anime doesn't seem to be getting picked up during library scan. 

**What version of Overseerr are you running?**
1.12

**To Reproduce**

Search for anime that is already within Plex.

**Expected behavior**
Like TV shows, expect "available". 

**Screenshots**
![image](https://user-images.githubusercontent.com/4349962/102846476-f91fc200-4407-11eb-8500-80f90c1fd598.png)

**Desktop (please complete the following information):**

- OS: win10x64
- Browser Vivaldi
- Version 3.5.2115.81

**Additional context**
Plex library is not using any 3rd party scanners or agent unlike #398 
![image](https://user-images.githubusercontent.com/4349962/102846544-22d8e900-4408-11eb-92ba-ccdec4fdc408.png)

**Comment by samwiseg0** [comment] 2020-12-22 03:48
Isn't that the new beta Plex scanner that is being tested?

**Comment by modem7** [comment] 2020-12-22 03:50
Unsure, whilst I am on the beta Plex release, I only have two options, Absolute Series Scanner (3rd party) or the Plex Series Scanner (same one as the TV series which are working as expected).

![image](https://user-images.githubusercontent.com/4349962/102846795-d7730a80-4408-11eb-9ac3-203e89dd4df0.png)

**Comment by samwiseg0** [comment] 2020-12-22 04:00
Are you running this because I don't even have that option?

https://forums.plex.tv/t/new-plex-media-server-tv-show-series-scanner-and-agent-preview/665778

**Comment by modem7** [comment] 2020-12-22 04:03
Not yet, I'm still on 1.21.1.3830 with no custom modifications bar the hama agent (which I'll be removing at some point as I don't actually use it anymore)

**Comment by sct** [comment] 2020-12-22 04:08
![image](https://user-images.githubusercontent.com/234213/102847886-cf41bc00-4456-11eb-9c3f-0b7c43aeeefd.png)
My TV library doesn't have that option either 🤔

**Comment by samwiseg0** [comment] 2020-12-22 04:09
> I haven't had the option to upgrade my library like I did with the new movie scanner.
What does this mean? This makes me think you are running the beta since that is what is in the forum post. 

I do not have that option and it clearly says is the new agent in your screen shot. This is a dupe of https://github.com/sct/overseerr/issues/378. You will need to run the standard TMDb or TVDb agents

**Comment by samwiseg0** [comment] 2020-12-22 04:19
Can you pull the XML of at least 2 items that are failing for us?

Go to the item git get info. Then view XML

![Screen Shot 2020-12-21 at 11 18 28 PM](https://user-images.githubusercontent.com/2241731/102848501-f2cb1f00-43e2-11eb-819b-19c6c9d9fa33.png)

**Comment by modem7** [comment] 2020-12-22 04:29
You were right, something was definitely weird with the agents. I've just removed Hama and I get as you do now. 

https://gist.github.com/modem7/14d4db8a4c590b168468a4416c9ca4b2
https://gist.github.com/modem7/b4593e9552315ea2ab854c526961b40e

**Comment by samwiseg0** [comment] 2020-12-22 04:39
Looks like your metadata is still hama `guid="com.plexapp.agents.hama://tvdb-267440/1/1?lang=en"`

You will need to rescan you library with the new agent. This could take a long time depending on the size of your library. If you want to do a quick test you can "fix match" a few items and they should match in overseerr.

**Comment by sct** [comment] 2020-12-22 04:39
The bad news is that your guid's look like this `guid="com.plexapp.agents.hama://tvdb-267440/1/1?lang=en"` Which is not a standard guid format for Plex.

The good news is, that it appears a tvdb can still be pulled out of that string. Which is all that should be necessary to do the matching required in Overseerr. I can add support for this scanner.

If you would like, I can push a test build with this scanning enabled and you can try it?

**Comment by modem7** [comment] 2020-12-22 04:40
I noticed that myself, I'll get things done properly in the meantime, but it seems that even if you switch away from Hama, it keeps the metadata in there. 

That would certainly be a good test, and it may at least partially resolve some of the other issues that some are having due to Hama!

**Comment by sct** [comment] 2020-12-22 04:43
Okay let me build it now.

**Comment by modem7** [comment] 2020-12-22 04:46
For others who come across this, the easiest (albeit laborious) way to sort the metadata out if you're not using Hama anymore is to un-match and re-match the series/movies in question. 

Seems that you don't need to clear bundles or optimise database at this point, but it'd be a good idea to do it once you're finished.

**Comment by sct** [comment] 2020-12-22 04:47
Ok @modem7 its building now. (See referenced commit). Once that develop tag is pushed can you pull it and give another full sync a go? (Disable other libraries so it just runs a sync on the one for now to save time)

**Comment by modem7** [comment] 2020-12-22 04:48
Sure thing, will do!

**Comment by modem7** [comment] 2020-12-22 05:01
Still no go unfortunately w/ the dev build.

However, I can confirm that un-matching and re-matching to tvdb does at least work. 

I gotta head to sleep as it's 5am here, but can pick this up in the arvo?

**Comment by sct** [comment] 2020-12-22 05:06
Oh dang you deleted your previous gists? Still need those to debug this haha.

Anything coming up in logs with the latest develop tag with LOG_LEVEL set to debug when you run the full sync?

**Comment by modem7** [comment] 2020-12-22 05:06
No worries, let me up some new gists now before I head off!

**Comment by sct** [comment] 2020-12-22 05:10
Oh looks like the tvdb is not guaranteed. 👉 `guid="com.plexapp.agents.hama://anidb-13743/1/2?lang=en"`

**Comment by sct** [comment] 2020-12-22 05:13
Not much I can do with that. As with what i said in #398 you will have to wait for the optional title/year fallback matching (which will be optional and disabled by default)

**Comment by sct** [comment] 2020-12-22 05:13
Because this discussion progressed further I will close #398 and move discussion here.

**Comment by modem7** [comment] 2020-12-22 05:15
If I recall correctly (and at 5am, don't quote me on it), hama allows for tvdb and anidb values. 

But I think we have a suitable workaround in place currently as well which should allow features to work (switch to TVDB and un-match/re-match) until the title/year fallback. 

Appreciate all the help though! Thank you!

**Comment by sct** [comment] 2020-12-22 05:18
Well, the change I pushed will actually match any id's that do use tvdb from hama. So there is that at least. 😁

**Comment by DJScias** [comment] 2020-12-22 17:15
I've put in an issue with HAMA to ask if there's no way to expose the TVDB IDs (and possibly AniDBs) from the animes that got matched through AniDB: https://github.com/ZeroQI/Hama.bundle/issues/436

This mostly from the fact that HAMA uses a function (`AniDBTVDBMap`) that links TVDB <---> AniDB. Perhaps it can benefit Overseerr and other programs in the future.

**Comment by DJScias** [comment] 2021-01-08 09:44
Now that this is merged, is it just applying the new update and running a manual full sync?

Or how would we start with getting the mapping to work on a library?

**Comment by omeryagmurlu** [comment] 2021-01-09 21:08
> Now that this is merged, is it just applying the new update and running a manual full sync?
> 
> Or how would we start with getting the mapping to work on a library?

It was the former for me

**Comment by sct** [comment] 2021-01-10 11:31
I think it's safe to close this now thanks to #538

**Closed by sct** 2021-01-10 11:31 UTC
Labels: bug, priority:low, topic:backend
