### ISSUE TITLE
Request filter/sorting to remember last known state

### ISSUE THREAD

**Issue by dphildebrandt** [sct/overseerr#1145] opened 2021-03-10 17:45 UTC
#### Description

Every time you go to the Requests page it defaults the filter to `Pending`. For those who have auto-approve enabled, this is not a useful state and it is annoying to switch to your preferred filter/sorting each time.

#### Desired Behavior

Let the filter, sorting, and 'results per page' remember the last known state.

At the very least, it should default to `All`, rather than something more specific.

**Comment by TheCatLady** [comment] 2021-03-10 18:03
Duplicate of #616

**Closed by TheCatLady** 2021-03-10 18:03 UTC
Labels: awaiting-triage, type:enhancement
