### ISSUE TITLE
Ability to select a default profile/server for a user

### ISSUE THREAD

**Issue by baty0man** [sct/overseerr#1128] opened 2021-03-08 23:18 UTC
#### Description

I would love the ability to define a default server/profile per user. Some of my users do not have great bandwith and I'd like for them to be assigned to a 720p profile without them having to select it manually when requesting a movie. 

#### Desired Behavior

In a user's settings, an admin can select a default server/profile for that user.

**Comment by TheCatLady** [comment] 2021-03-08 23:22
Duplicate of #609

**Closed by TheCatLady** 2021-03-08 23:22 UTC
Labels: awaiting-triage, type:enhancement
