### ISSUE TITLE
Custom Donation Button

### ISSUE THREAD

**Issue by bweezy21** [sct/overseerr#2799] opened 2022-06-02 16:43 UTC
### Description

Allow admins to add a button to redirect to a donation link of their choice.

### Desired Behavior

In the settings allow admins the ability to add a donation button linking to a donation service of their choice. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-06-02 17:11
Duplicate of #2624

**Closed by TheCatLady** 2022-06-02 17:11 UTC
Labels: type:enhancement, awaiting-triage
