### ISSUE TITLE
Support Base URL (Like Radarr, Ombi and Sonarr etc)

### ISSUE THREAD

**Issue by Swiftnesses** [sct/overseerr#725] opened 2021-01-22 20:11 UTC
Good day,

Thanks for the great tool (currently testing it as an alternative to Ombi).

Is it possible to support a 'base URL' for example '/overseerr' - I use Organizr and have my apps proxied at locations like:

https://dashboard/overseerr

Many thanks in advance.

**Comment by samwiseg0** [comment] 2021-01-22 20:16
Dupe of https://github.com/sct/overseerr/issues/274

**Closed by samwiseg0** 2021-01-22 20:16 UTC
Labels: type:duplicate
