### ISSUE TITLE
"Watch Trailer" (on mobile browser) opens unnecessary blank tab in browser

### ISSUE THREAD

**Issue by marchershey** [sct/overseerr#1576] opened 2021-05-05 05:31 UTC
#### Description

On a mobile browser, when you press "Watch Trailer," a blank, new page tab is opened, then the user is redirected to the YouTube app. Then when you switch back to the browser, you need to delete the newly opened blank tab and go back to Overseerr

#### Version

1.23.2

#### Steps to Reproduce

(ON MOBILE DEVICE BROWSER)

1. View Media (Movie or Series)
2. Tap "Watch Trailer"

#### Expected Behavior

When the user clicks Watch Trailer, blank tab should not be created. Should redirect to YouTube / open YouTube app without blank tab. 

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** smartphone
- **Device:** iPhone 11
- **OS:** iOS 8.1
- **Browser:** Chrome & Firefox tested

**Comment by marchershey** [comment] 2021-05-05 05:37
**Solution:**

1. Embed the trailer on the page
2. Open model with the trailer

**Comment by TheCatLady** [comment] 2021-05-05 12:58
Duplicate of #962

**Closed** 2021-05-05 12:59 UTC
Labels: type:duplicate, type:enhancement
