### ISSUE TITLE
Send `Series Now Available` email when a running series is upto date

### ISSUE THREAD

**Issue by afzaal-ameer** [sct/overseerr#2187] opened 2021-10-12 10:55 UTC
#### Description

Currently, if someone requests a running series, they'll have to wait until the series finishes before they get the `Series Now Available` email.

#### Desired Behavior

For **presently** running series, if all episodes till the **present** are ready, an email should be dispatched that the series is available.
- Presently/Present refer to the time the series is requested.

**Comment by TheCatLady** [comment] 2021-10-12 11:00
Duplicate of #1477

**Closed as completed by TheCatLady** 2021-10-12 11:00 UTC
Labels: type:duplicate
