### ISSUE TITLE
Email notifications stopped working

### ISSUE THREAD

**Issue by natebur** [sct/overseerr#1327] opened 2021-03-30 11:51 UTC
#### Description

In the latest update, email notifications stopped working.

#### Version

1.21.1

#### Steps to Reproduce

NA

#### Expected Behavior

When an event matching the notifications I specified occurs, an email should be sent

#### Screenshots

NA

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** desktop and smartphone 
- **Device:** iPhone 11 Pro and surface pro
- **OS:** iOS 14 and windows 10
- **Browser:** chrome, edge, and privacy browser 

#### Additional Context

This worked previously, but just stopped working in the latest update

**Comment by sct** [comment] 2021-03-30 12:03
Duplicate of #1324

**Closed by sct** 2021-03-30 12:03 UTC
Labels: awaiting-triage, type:bug
