### ISSUE TITLE
SAML Auth

### ISSUE THREAD

**Issue by takeittothemax** [sct/overseerr#3099] opened 2022-10-28 17:23 UTC
### Description

Implement the ability for us to use SAML SSO with our local users. It's nice to have everything self hosted including auth. 

### Desired Behavior

Using own hosted or 3rd party auth provider to SSO into the application with own local user db. Something like keycloak, Azure, Okta. Could even implement a base permission set and allow it to provision users.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-10-28 17:37
Duplicate of #1638

**Closed by TheCatLady** 2022-10-28 17:37 UTC
Labels: type:enhancement, awaiting-triage

**Comment by takeittothemax** [comment] 2022-10-28 17:44
Another option could be open id or trusted headers with Authelia too.
