### ISSUE TITLE
Sort Requests alphabetically

### ISSUE THREAD

**Issue by saxx0n** [sct/overseerr#3933] opened 2024-09-15 13:35 UTC
### Description

I admittedly use Overseerr in a non-typical format (no sonarr/radarr sources), instead using it as a "what else do I need for my collection" type deal.  As such trying to find a movie after it has been requested can be a challenge, and not having a way to go alphabetical is super frustrating.

### Desired Behavior

Add a dropdown option to the requests page to allow for it to be sorted alphabetically.  

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2024-09-15 15:52
Closing as a duplicate of #3576

**Closed by danshilm** 2024-09-15 15:52 UTC
Labels: type:enhancement, awaiting-triage
