### ISSUE TITLE
Allow users to see downloads without "Manage requests" permission

### ISSUE THREAD

**Issue by kevkevhd** [sct/overseerr#3002] opened 2022-09-03 18:14 UTC
### Description

A big pain in my butt is my users requesting something but not knowing if radarr/sonarr could actually find something and not knowing how long a download will take etc.

### Desired Behavior

You can see the download progress via overseer today if you have the "Manage requests" permission but this also allows users to delete their own and others requests.  I would like a specific permission to see download progress only, without the ability to remove requests. 
![Screenshot 2022-09-03 201202](https://user-images.githubusercontent.com/13189552/188283194-31fc126d-a33c-4dfd-9f80-17e2bdcbdb6b.png)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-09-03 18:25
Duplicate of #994

**Closed by TheCatLady** 2022-09-03 18:25 UTC
Labels: type:enhancement, awaiting-triage
