### ISSUE TITLE
REQUEST: Sorting ability on content screens

### ISSUE THREAD

**Issue by kingfenix** [sct/overseerr#2477] opened 2022-01-25 20:24 UTC
### Description

Im always frustrated when I want to find new content and I have to scroll screen by screen to find things.

### Desired Behavior

Add sorting drop down or control in the content screen so that I could tell it to sort by various fields, such as "First Air Date" or Title, etc...Also some filtering mechanism to say only show "Returning Series" for example.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2022-01-25 20:29
Duplicate of #459

**Closed by TheCatLady** 2022-01-25 20:29 UTC
Labels: type:enhancement, awaiting-triage

**Comment by cparello** [comment] 2022-10-04 03:32
please add sorting @TheCatLady
