### ISSUE TITLE
Users not receiving 'Media Available' notification emails.

### ISSUE THREAD

**Issue by cliny** [sct/overseerr#1324] opened 2021-03-30 01:43 UTC
#### Description

Users not receiving 'Media Available' notification emails.

#### Version
develop-1b129c0b3863ea3c5ad34c66b3ace5d09cd4e391

#### Steps to Reproduce

1. Request movie as non-admin user.
2. Movie becomes available
3. No 'media available' notification email is received by requester, in spam nor inbox

#### Expected Behavior

an email to say it is available should be received

#### Device

- **Platform:** desktop
- **OS:** arch linux
- **Browser:** firefox

#### Additional Context
It still works in the official non-develop version of docker.

Emails not in spam or inbox.

Auto-approved and test emails are working fine.

**Comment by sct** [comment] 2021-03-30 01:44
Do you have any logs of the failure?

**Comment by cliny** [comment] 2021-03-30 01:46
> Do you have any logs of the failure?

My logs stop at around 1am this morning for some reason? it is 12:45pm here now (australia/melbourne)

**Comment by sct** [comment] 2021-03-30 01:47
The logs don't just stop? Are you sure it didn't rotate to a new file? We rotate logs daily.

**Comment by cliny** [comment] 2021-03-30 01:48
> The logs don't just stop? Are you sure it didn't rotate to a new file? We rotate logs daily.

2021-03-30T01:22:24.688Z [info][Notifications]: Sending notification for MEDIA_AVAILABLE 
2021-03-30T01:22:24.689Z [debug][Notifications]: Sending email notification

**Comment by sct** [comment] 2021-03-30 01:50
Looks like it's sending fine? It must be something with your configuration.

**Comment by cliny** [comment] 2021-03-30 01:53
> Looks like it's sending fine? It must be something with your configuration.

It does look fine. I'm not sure why I'm not receiving them though, I've checked inbox and spam of the correct email accounts. In fact I've tried it on about 4 users now. And my email server details are fine because I'm receiving test emails and auto-approved emails. Hmm I don't know?

**Comment by sct** [comment] 2021-03-30 01:56
I am not sure. My guess is something with your email server has no problems sending to your own personal accounts but is having issues with external accounts? Either way, I confirmed approved emails are working on develop. Marking this as a support request. You can reach out for more help in Discord and hopefully we can get this solved.

**Comment by sct** [comment] 2021-03-30 12:00
I was able to track this down an actual bug! I am getting a fix in now!

**Closed** 2021-03-30 12:03 UTC
Labels: severity:high, type:bug
