### ISSUE TITLE
Sometimes Telegram notifications get sent, sometimes they error out with Error 400

### ISSUE THREAD

**Issue by lightmaster** [sct/overseerr#3292] opened 2023-01-29 02:06 UTC
### Description

I can send a test Telegram notification to a Telegram channel without any issue.

- When someone requests new content, sometimes the request notification goes through, and sometimes it fails with a status code of 400.
- When a request gets approved, if the requested notification went through, then the approval notification goes through, if the requested notification failed, then the approval notification fails with a slightly different error (see logs).
- When media becomes available, errors out with a status code of 400

I was using the stable branch, version 1.31.0. I updated a couple days ago to the develop branch using snap to make sure this hadn't been fixed already.

### Version

8942eb8b7c4fa1d16aa2e72e8ba7120a653c9aa2

### Steps to Reproduce

1. Setup telegram to use a channel (may or may not error out on groups or individual chats?)
2. Have a user request any number of items
3. Watch some notifications arrive, and some of them fail to come in.

### Screenshots

![Overseerr Telegram Settings](https://user-images.githubusercontent.com/5307827/215299865-dba83e63-78e6-4d48-b3f8-c1fbb874aa89.png)

### Logs

```shell
2023-01-29T00:25:54.590Z [error][Notifications]: Error sending Telegram notification {
  "errorMessage":"Request failed with status code 400",
  "response": {
    "description":"Bad Request: failed to get HTTP URL content",
    "error_code":400,
    "ok":false
  },
  "subject":"Scooby Doo and The Zombies (2011)",
  "type":"MEDIA_PENDING"
}

2023-01-29T01:41:56.430Z [error][Notifications]: Error sending Telegram notification {
  "errorMessage":"Request failed with status code 400",
  "response": {
    "description":"Bad Request: wrong file identifier/HTTP URL specified",
    "error_code":400,
    "ok":false
  },
  "subject":"Scooby Doo and The Zombies (2011)",
  "type":"MEDIA_APPROVED"
}

2023-01-25T09:15:00.954Z [error][Notifications]: Error sending Telegram notification {
  "type":"MEDIA_AVAILABLE",
  "subject":"M3GAN (2022)",
  "errorMessage":"Request failed with status code 400",
  "response":{
    "ok":false,
    "error_code":400,
    "description":"Bad Request: wrong file identifier/HTTP URL specified"
  }
}
```

### Platform

desktop

### Device

Laptop

### Operating System

Windows 11

### Browser

Firefox

### Additional Context

Does not matter which device a user requests media from, but it forced me to answer those questions. If it makes a difference, my instance of Overseerr is running on Proxmox 7.3-4 as a Debian 11 LXC, installed using snap. It is a fresh install that was first set up approximately 5 days ago.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by DavidJuanes** [comment] 2023-02-12 13:21
Probably related to https://github.com/sct/overseerr/pull/3150?

**Comment by danshilm** [comment] 2023-02-23 09:21
Closing as a duplicate of #3064

**Closed by danshilm** 2023-02-23 09:21 UTC
Labels: type:bug, awaiting-triage
