### ISSUE TITLE
Discovery Recently Added Filtering

### ISSUE THREAD

**Issue by xInsertx** [sct/overseerr#1475] opened 2021-04-20 10:33 UTC
#### Description

Overseer shows all recently added media.

#### Desired Behavior

Match the filtering that Plex uses for media (library and allow/deny tags).

#### Additional Context

plex already does this really well, so I am hoping to match the behaviour. This would than tie into other advanced filtering requests, so that certain users only see what they should.

**Comment by samwiseg0** [comment] 2021-04-20 15:25
Duplicate of https://github.com/sct/overseerr/issues/1340. We should consolidate all the ideas for the discover page under one issue. 

Thanks!

**Closed by samwiseg0** 2021-04-20 15:25 UTC
Labels: awaiting-triage, type:enhancement
