### ISSUE TITLE
Block a show or movie from being requested

### ISSUE THREAD

**Issue by JoshNotWright** [sct/overseerr#2135] opened 2021-09-26 18:35 UTC
#### Description

I like requests being automatically accepted, but there are a handful of shows that get requested often that I don't want / can't find. 
#### Desired Behavior

It would be nice if I could click on a show or movie, and have an option to automatically deny requests for them. Maybe you could optionally enter a reason why it's blocked for the user to see if they try to request it.

**Comment by TheCatLady** [comment] 2021-09-26 18:46
Duplicate of #1744

**Closed** 2021-09-26 18:46 UTC
Labels: type:duplicate
