### ISSUE TITLE
Auto approve tv shows based on number of seasons

### ISSUE THREAD

**Issue by AlpacaDesu** [sct/overseerr#2729] opened 2022-05-02 01:28 UTC
### Description

Allow admins to set tv shows to get auto approved if number of seasons <= admin specified number

### Desired Behavior

have many users who request short mini series quite regularly (1-2 season) - I’d like those to get auto approved

but when someone requests a show with 10+ season, I’d rather review it manually before approval 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment] 2022-05-02 15:10
Duplicate of #1881.

Also, there would need to be more control over what determines a request to be automatically approved instead of just the amount of seasons since tv shows can have few seasons but a ridiculous amount of episodes in each. Or they can have a few seasons, but with each episode being more than an hour long.

**Closed by danshilm** 2022-05-02 15:10 UTC
Labels: type:enhancement, awaiting-triage
