### ISSUE TITLE
Allow Users to "Request" Notifications for Media Already Requested

### ISSUE THREAD

**Issue by Nealon01** [sct/overseerr#2262] opened 2021-11-05 03:54 UTC
### Description

When one user requests a show/movie, it get's marked as "Requested", and no one else can request it.  This isn't really an issue, except that if users wanted to receive an email notification when the show/movie was added, they can no longer get that.

### Desired Behavior

Could there be a way for users to "watch" an existing request, or even allow multiple users to request the same item?

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment] 2021-11-05 04:08
Duplicate of #789

**Closed by TheCatLady** 2021-11-05 04:08 UTC
Labels: type:enhancement, awaiting-triage
